### ISSUE TITLE
16 channel specific (maybe) problem

### ISSUE THREAD

**Issue by cjwiggins** [CMRR-C2P/MB#100]
I am having a problem which may be very specific to our setup. We have a 16 channel system, but are running with 8 channel coils. For reasons of the Siemens master channel, this means we actually do not use channels 1-8 and just use 9-16, with 16 the master channel. I have then set channels 1-8 to zero amplitude in the CP_mode.ini file.

When running the C2P sequence (CMRR_MB_EPI_VB17A-F37_R012b_Step2p3) on this system, all works fine if I am using a 16 channel coil. But with the above configuration the preparation fails on the slave console.
![cmrrprepare_zero](https://cloud.githubusercontent.com/assets/4072297/8958439/28bf7328-3605-11e5-8c5e-4b1b3db4e099.PNG)

I guessed that this was connected to the zero amplitude in the CP_mode file and sure enough, if I set the amplitudes to 0.01, I get a slightly different result:

![cmrrprepare_0p01](https://cloud.githubusercontent.com/assets/4072297/8958468/48d3da50-3605-11e5-94af-442814270107.PNG)

And if I set them to 1.0 the sequence runs. So obviously this is the problem. But how can I run this sequence with some transmit lines set to zero amplitude? I guess you would have the same problem if running only 4 channels of an 8 channel system.

**Comment by eauerbach** [comment]
This should be solved in R012c and later (clipped pulse detection is disabled for ptx)
