### ISSUE TITLE
Recon hanging on Prisma VD13D/R012b

### ISSUE THREAD

**Issue by rwmair** [CMRR-C2P/MB#102]
Eddie,

We've had a few instances now of the recon system hanging after many MB-BOLD scans have been run in quick succession. (This is in R012b on a Prisma running VD13D)

When first looking in TWIX, the "problem" scan will show "rip" for its state, while later scans will sit in the recon queue, not completing. I've had to reboot the MARS to make things work again. At this point, the "problem" scan now has "_state_clf" appended to its name. However, if the AdjCoilSense file is still on the MARS, its possible to retro-recon it and all later scans.

I'm wondering if this is a reoccurrence of the bug that was fixed in R012b as listed in the release notes. I couldn't find a description of the symptoms of that bug.

I have a SAVELOG I can send if needed.

Thanks,

Ross

![twix_clf_150921](https://cloud.githubusercontent.com/assets/6045245/10087263/d51d656e-62e0-11e5-8fc3-62711cb41059.png)

**Comment by eauerbach** [comment]
We have experienced this problem on our Prisma and it is an open issue with Siemens, but in our case it is clear it also occurs with product sequences. Ideally if this happens you should do a savelog before rebooting and send it to Siemens so they can have a look at it.

To recover your data, you can retro recon; if you have rebooted and it complains about the adjustment data, use this command first:

AST -SimulationSystem ON
