### ISSUE TITLE
TTL pulse per volume

### ISSUE THREAD

**Issue by tang0522** [CMRR-C2P/MB#105]
We are setting up concurrent EEG-fMRI experiments using MB. We need to get the TTL pulse by each TR. We observed that we got TTL pulse every two TRs, e.g. every two seconds if TR=1s, or every three seconds if TR=1.5s. When we used the general EPI sequence, we can get TTL pulse every TR. So we wonder whether there are settings or options we should change in the MB protocol? Many thanks!!!

**Comment by eauerbach** [comment]
On the special card there is an option for "Triggering scheme" which allows you some options for how the triggers are sent. If you want one trigger per volume like the product sequence, you shouldn't touch this parameter--just leave it at the default "Standard".

**Comment by tang0522** [comment]
Thanks for your helps. The problem is solved! 

Yingying
-------------------------------------------
Yingying Tang, PhD
Department of EEG & Imaging
Shanghai Mental Health Center
