### ISSUE TITLE
MB for PrismaFit/VE11

### ISSUE THREAD

**Issue by PimUA** [CMRR-C2P/MB#106]
We have a new installation of a PrismaFit with VE11, will the MB sequences become available for this platform?

Best, 

Pim

**Comment by eauerbach** [comment]
Yes, we have sent out versions for VE11A and VE11B to a few sites for testing. It looks like there are some minor UI issues that still need to be worked out, but otherwise the sequences seem to be running fine. If you would like to test them send an email to Essa or me.

**Comment by halfSpinDoctor** [comment]
Hi Eddie, we are getting a VE-Prisma installed at Oxford soon. I will e-mail you and cc Essa to ask for the trial version of VE. I understand it is experimental at this point.

BW, -Sam

**Comment by eauerbach** [comment]
R013 is released with VE11A/VE11B versions
