### ISSUE TITLE
R013 SE-EPI will not open sequence with fake multiband > 1 and IPAT > 1 on VD13C-SP2

### ISSUE THREAD

**Issue by Jolinda** [CMRR-C2P/MB#108]
This is with version R013 on VD13C SP2. If you have exposed the "fake multiband for singleband options" and open a sequence that has been set up with both IPAT > 1 and fake multiband > 1, you get an error message ("protocol has been fixed") and the sequence reverts to the default protocol. This was not the case for R012. If it has just one or the other it’s fine. If you open a protocol with either IPAT > 1 or fake multiband > 1 (but not both), you can then edit it to have both values > 1 and run it.

**Comment by eauerbach** [comment]
I will look into it and see if there is an easy fix, but eventually I want to eliminate this option... The way it is implemented internally is ugly and (obviously) fragile. Can you do without it? I think in most cases where it was used in the past it is possible to prescribe a "real" multi-band protocol and just use the single-band reference scan.

**Comment by Jolinda** [comment]
I’m sure we can. We’re using the sequence to create a field map following the recommendations for the human connectome protocols, which said to use the fake multiband setting. I never checked to see how much difference it made to use it, but I’m pretty sure the field maps we’re getting with fake multiband turned off are good enough for our purposes.

**Comment by eauerbach** [comment]
This should be fixed in R014.
