### ISSUE TITLE
VE11 upgrade for Skyra includes Tesla K10 GPU

### ISSUE THREAD

**Issue by lucijj** [CMRR-C2P/MB#110]
We just upgraded our Skyra to VE11A.  The new MARS includes a Tesla K10.  The first thing I did was install the sequence, and reboot the MARS to look for C:\MedCom\MCIR\med\config\eja_hardware.ini.  It wasn't there.  Has this feature been eliminated?  If so, is there another way to determine if the GPU is being used for recon, or can you confirm that the K10 is a supported GPU?

**Comment by eauerbach** [comment]
GPU support is currently not enabled for VE11A and VE11B. I should be able to get working on that soon. However, K10 is fundamentally not a good GPGPU (abysmal double precision performance) and I'm surprised Siemens went that route...or not...well, actually I am. Even when it was first released (2012), it wasn't very popular, and it hasn't gotten better with age. NVIDIA must have had a warehouse full of them that nobody else wanted...

Anyway, I have done some tests on a K8 (1/2 of a K10) and it is significantly slower than just using the CPUs (for reasonably modern CPUs). So currently if I detect a K8 or K10 I default to CPU processing. But maybe K10 is good enough for some applications. Only the kernel calculation requires double precision; the unaliasing is single precision. For long scans perhaps it catches up, since currently only one kernel calculation is performed at the start of the scan (this may change in the future). I don't have an option to do the kernel calculation on CPU and unalias on the GPU, but maybe that would be useful.

**Comment by lucijj** [comment]
OK, well, in that case, maybe it's worth trying upgrading the GPU like we did under VD13 and the Tesla C1070, going to a C2070?  It looks like both the K40 and K80 use the same drivers and CUDA libraries as the K10.  I can't find reliable comparisons of the K10 vs either the K40 or K80.  But, I did find some K40 vs. CPU (parallel on a recent 10-core Xeon).  It looks like the K40 is 5-6 times faster for doubles and 3-4 times faster for singles.  Using nVidia's published metrics for K40/80 benchmarks, the K80 is about 30-40% faster than the K40.  But with a street price $1,200 higher than the K40, I'm not sure the K80 is worth the dough.  

Of course, what I'm most interested in is realtime functional feedback, so every little bit helps.  If you'd like to try it, I'd be happy to buy a K40 and make it available in our Skyra for beta testing.  As far a long scan performance goes, for 48 BOLD slices, MB=2, TR=1500, 128x128 matrix, the first images arrive about 30 TRs behind, but quickly catch up to about 20 TRs behind.  Regardless of how long the scan is (up to 15 minutes), it keeps up at that point.  So, if we can speed up the kernel calculation by a factor of 4 and unaliasing by 2, we would be near realtime recon by TR #15-ish.  That's perfectly acceptable, and I'm willing to help in any way I can to get there.

**Comment by lucijj** [comment]
I promised my users I'd ping you to see if there was any progress on GPU support.  Again, if we can help on that front at all, we will.

**Comment by eauerbach** [comment]
I should have something soon. Do you still only have a K10? I can send you a version to test with the K10 when it is ready; maybe it will work ok, but I wouldn't be surprised if you want to eventually find a K20 or K40.

Can you verify for me that VE11A is using CUDA 5.5? If you look in the directory ```C:\MedCom\MCIR\Med\modules\nvidia``` do you see a couple NVIDIA installers for driver version 319.37?

(FWIW, K80 is not supported until driver version 340 or so.)

**Comment by lucijj** [comment]
That is great news!  I haven't purchased a new GPU yet, but I definitely will.

The installers you noted do exist in that location, and the version numbers match.

**Comment by eauerbach** [comment]
The new release (R014) early next week will include GPU support for VE11x and will also support a hybrid CPU/GPU option to attempt to make good use of GPUs like K10 which do not support double precision. Basically the kernel will be calculated on the CPU and the unaliasing will happen on the GPU. The first image will be delayed, but hopefully it will catch up.

**Comment by lucijj** [comment]
Hey Eddie:

That's great news!  Thanks for everything you've done to make this 
wonderful.

Just to be clear, though - do you foresee any problems with upgrading 
our GPU to a K40?  I think the nVidia driver Siemens uses will handle 
that, but I want to make sure there isn't anything specific in your code 
that would cause it to barf.

Also, will the feature that sends pixel data via the second network 
connection (that we use for real time) be available?

Thanks again,
Jeff

**Comment by eauerbach** [comment]
I don't think there is any (technical) problem upgrading a VE11x system to a K40 (or two). K80 and newer would not be supported, however.

The remote recon server which you have used to export the data in real time is available, but depending on which model MaRS you have you may need to add a network card. I'm not sure for your purposes if a 10 GbE card is necessary; maybe 1 GbE is fine. But some of the MaRS models do not have any existing spare network ports.

I will be releasing an updated version of the server program to support the new reconstruction options available with R014, but for your purposes the old/current version would still work.

**Comment by lucijj** [comment]
Great.  Thanks.

I have the 10Gb/s card installed, and we were using it under VD13, but 
we haven't been able to do realtime since upgrading to VE11 since the 
recon times are so much slower on the CPU.  We'll be looking forward to 
getting it back up and running.

Jeff

**Comment by jpyles** [comment]
Would the Tesla K40 be recommended for a remote recon machine for a VB17A Verio system as well? Any other advice on the specs for the remote recon Linux box? We're looking at a System 76 Silverback. Thanks!

**Comment by lucijj** [comment]
I just installed R0014 with a Tesla K40 GPU.  The sequence correctly identifies the K40, and reports GPUComputeCapability = 3.5.

I don't have scanner time to do careful recon time measurements right now, but just sitting at the console and watching the inline display, I can see a significant performance improvement.  Using 60 slices, TR = 1200, MB factor = 4, 32 channel coil, it takes 7 TRs to return the first images, but by the 10th TR, all the lagged volumes are loaded, and the display maintains a 1TR lag with visually instantaneous updating upon completion of a volume acquisition; which is exactly what we were used to in VD13 with the old GPU (a K1000, I think?).  Perhaps even more importantly, the 7TR lag and catchup is fully reproducible (whereas before, the number of volumes before first images would take 10-20 TRs, and there was no telling how long it would take).  The recon is essentially realtime again, which opens up our previous avenues of research.

I'll be able to get some quantitative latency/lag measurements made before the end of the week, and I'll post them here if you want.  Thanks again for adding this feature!

**Comment by eauerbach** [comment]
That is good to hear!
