### ISSUE TITLE
VD19A trio Gradient Power Amplifier error

### ISSUE THREAD

**Issue by ZigorDiaz** [CMRR-C2P/MB#113]
I am trying to used MB in diffusion sequence in VB19 Trio. During runing cmrr_mbep2d_diff sequence is stopped. May be that is any parametre wrong or gradiente power error. Can i send us complete savelog?
![issue_01212016](https://cloud.githubusercontent.com/assets/16815048/12476840/531c176e-c02c-11e5-879e-f2d2006f87a2.JPG)

Thank you very much

**Comment by ZigorDiaz** [comment]
f i apply diffusion scheme "bipolar" the sequence runs ok, but the quality image it is so poor.
I works with 3 different B values (1000,2000, 2700) but the issue persists in all of them.
The diffusion mode it is free with 68 directions.
Thanks

**Comment by ZigorDiaz** [comment]
somebody can help me to solve the issue?

**Comment by eauerbach** [comment]
When you are using a free direction set, you need to make sure that your directions are arranged in a way that minimizes the duty cycle of the individual axes. For example, if you have a vector (0,0,1), the next vector would ideally be (1,0,0) or (0,1,0); i.e., if you are using 100% of a given gradient for one vector, do not follow it with a vector that uses 99% of the same gradient.

On VD13/VE11 the sequence will attempt to predict duty cycle and cooling problems with your direction sets and force you e.g. to increase TE/TR. On VB17/VB19 the sequence will run, but eventually crash when a hardware limit is reached. In both cases it is best to optimize the direction sets beforehand.
