### ISSUE TITLE
VE11B R013 sequences stopped running (ICE error)

### ISSUE THREAD

**Issue by lastables** [CMRR-C2P/MB#116]
The CMRR multiband sequences (all 3: bold, diff, & se) stopped running on our Prisma Fit on 4/1 in the middle of a scan session. The prescan calibration scans all run fine, as does the stimulation monitor (giving one the option to change rise time, etc), but when the actual sequence is about to start, I get a red line through the recon icon & the error message says: 
"Pipeline preparation failed: Composer error in protocol access service" (Domain = MRI_COS). There's also a yellow line through the FID icon and the error message says "Preparation of image reconstruction system failed".

These error messages started popping up in the middle of my scan session, after I'd successfully run several CMRR bold scans. The only thing that happened during the session is that I pulled the table out to change phantoms (from a squash to a Siemens bottle phantom). The other change that happened yesterday (about an hour earlier) is that the scanner finally got on the network and could talk to Siemens headquarters - I have no idea if that could be a factor or not. The problem persists after a full shutdown & reboot & after reinstalling the sequences. I created a SaveLog  - if you'd like to see it, let me know where to send it.

These are R013 sequences running on VE11b on a newly installed Prisma Fit (has only been up for 2 weeks).

Thanks!
Lara

**Comment by eauerbach** [comment]
Yes, there was a problem with the initial build of R013 for VE11B. If you download and install the latest build (dated 4-Apr-2016) this is fixed.

**Comment by lastables** [comment]
Great, thanks!

**Comment by mscohen** [comment]
Using VE11B, with a download from two days ago (should be current!), we are able to run and reconstruct all of the cmrr_mbep2d_* sequences except cmrr_mbep2d_diff. With the diff sequences, we receive a MRI_PRC error, and MRI_MSR error.

This problem occurs even with the sequences reduced to a minimum: IPAT off, 6 directions (standard gradient table), long tr with 4 slices. With multiband excitation tuned OFF, however, the sequence runs to completion regardless of IPAT settings.

Is there an error in the ICE program? Is there an update?

I noticed that the creation dates for the CMRR_MBIceProgram2D.ipr and CMRR_MBIceProgramDit2D.ipr both are 3/28/14, whereas the dll, eve and so files are dated 4/4/16.

Thank you

I should say that the image quality of this rev of the CMRR sequences has been outstanding.

**Comment by mscohen** [comment]
We hypothesized that this was related to the diffusion vector files. We transferred a DVS file from another Prisma-fit scanner with the same VE11B software, however these failed as well.

Is there an array processor firmware upgrade needed for this?

Do you have an update on progress for this? Thanks.

**Comment by eauerbach** [comment]
I would have to look at a savelog to see what is going on in this case, since nobody else has reported anything similar. One thing I would suggest is to make sure that the Siemens online postprocessing is disabled (only the "Diff. weighted images" and "Mosaic" checkboxes should be checked), since this is the most likely source of errors in the ICE chain.

**Comment by mscohen** [comment]
It is working now. As best I can tell, this relates to the Resolution->Filter Image->Dynamic Field Corr. option. Turning that off allowed the scan to run to completion.

I will send along a saved log of the crashed sequence by separate post. 

Did you happen to see my note about the physio recording option?

Mark S. Cohen
Staglin Center for Cognitive Neuroscience
Room C9-420
Semel Institute for Neuroscience & Human Behavior
760 Westwood Plaza, Los Angeles, CA 90095

mscohen@g.ucla.edu
310-980-7453
http://tinyurl.com/mscohen
http://www.ucla-cir.org
