### ISSUE TITLE
Change in image number output

### ISSUE THREAD

**Issue by jlc8g** [CMRR-C2P/MB#117]
Good Morning,   We have a Siemens Trio, VB17. Our most recent WIP expired and have downloaded the new sequence, cmrr_mbep2d_diff. The old sequence was outputting 129 images, the new sequence is outputting 7482 images. Can anyone tell me what I can change to make the image numbers similar to 129?  Thank you!

**Comment by eauerbach** [comment]
Did you change the protocol? I would guess most likely you do not have the **Mosaic** option checked on the **Diff** card. If you are using **MDDW** mode, you have to define at least two **Diff. Weightings** (one is normally b=0) for the checkboxes to be enabled. For best performance, select only the **Diff. weighted images** and **Mosaic** checkboxes.

**Comment by jlc8g** [comment]
Mosaic was not selected. Perfect! Thanks! Jaime Castle-Shifflett
