### ISSUE TITLE
Variable b0 on diffusion sequences

### ISSUE THREAD

**Issue by gbook** [CMRR-C2P/MB#118]
We are using the MB diffusion sequence on a Siemens Skyra. We specified 74 directions, with a single b0 of 900. When converting the DICOM to Nifti, using dcm2nii, we get the usual .bvec and .bval files. The .bval file contains all kinds of b0's, ranging from 5 to the expected 900. Why are they varying? Is there a way to keep the b0 constant?

**Comment by eauerbach** [comment]
There are a few different options you can specify for the way vectors are normalized (or not) when read from .dvs files. I have not modified this behavior at all from the product implementation, so you are probably best served referencing the description of the file format in the manual (which I helpfully excerpted and included in the C2P .zip file as DiffusionVectorSetsVD13.pdf).

Also note that the b-value stored in the DICOM images is the "true" b-value of the acquisition, which may not match exactly what you asked for. For example, there is really no such thing as a b=0 scan. The nominal b=0 scans have spoiler gradients around the refocusing pulses which apply a small amount of diffusion encoding along the slice direction, and this is reported in the DICOM images (these are probably the b=5).
