### ISSUE TITLE
Sparse TR scheme for quiet periods in time series

### ISSUE THREAD

**Issue by BenInglis** [CMRR-C2P/MB#121]
Any chance we might get sparse sampling in a future version? Ideally just the read and phase encode gradients would be disabled during "quiet" TRs, leaving just slice select gradients which make clicks. We've found (on a version of ep2d_bold) that options to set independently the number of quiet TR periods and fully sampled TR periods gives good flexibility for, e.g. auditory fMRI, while keeping the T1 steady state approximately constant. For example, (5,2) would yield repetitions of five regular MB-EPI volumes interspersed with two quiet volumes.

**Comment by eauerbach** [comment]
I have included this option in R014, which should be released early next week.
