### ISSUE TITLE
Analysis of complex phase time series - low frequency oscillations!

### ISSUE THREAD

**Issue by pfannmoe** [CMRR-C2P/MB#122]
Dear Experts,

I am using the current multiband gradient-echo EPI sequence for BOLD imaging with:

MB = 6
voxel size = 1.5 mm isotropic
Siemens Verio 3 Tesla Scanner
VB17A. 

The GLM analysis of the magnitude images works fine and the results are all reasonable.I am trying to include the complex image phase in my analysis. Currently, I find low frequency oscillations with f < 0.05 Hz in the phase time series. Those cause a lot of trouble in my analysis. Does anybody have an idea about the origin of those oscillations? Do I have to set some particular options in the sequence protocoll if the phase is of interest? Any help is highly apreciated. 

Yours pfannmoe

**Comment by halfSpinDoctor** [comment]
It might be worth seeing how stable the main magent/shim is on your system. This can be done quite easily by running a series of basic single voxel spectroscopy scans (SVS) on a phantom every 5-10s (if the oscillations are 0.05 Hz, the period should be ~20s).

You can accomplish this by setting up the SVS scan on the basic sphere phantom, TR=5 or 10s, and many averages. If you have the tool to read raw TWIX data, you should be able to get an FFT and centre frequency of each average individually.

You might also want to try this after a period of "rest" where the scanner is sitting idle, then compare it to a period after you have run 10-20 minutes worth of the BOLD sequence first (to heat up the gradients) and see if this has any impact.

Best wishes,
Sam

**Comment by pfannmoe** [comment]
Dear halfSpinDoctor,

thank you very much for your advise. This is something I need to consider. As soon as I have news on this issue it will be posted here.

Yours pfannmoe
