### ISSUE TITLE
clipped RF warning on Prisma for HCP Lifespan protocol

### ISSUE THREAD

**Issue by huchengMRI** [CMRR-C2P/MB#125]
Hi, I implemented HCP Lifespan protocol on Prisma-fit. We got clipped RF pulse warnings for both fMRI and DWI sequences. The warning disappeared if I significantly increased the duration of the RF pulse from the default value of 2560 us. Is this the right way to do? 
Thanks!

Hu

**Comment by eauerbach** [comment]
Yes.
