### ISSUE TITLE
VE11A r014

### ISSUE THREAD

**Issue by ryansangill** [CMRR-C2P/MB#127]
Has the VE11A version been discontinued.  We're still waiting to be upgraded to VE11C (Skyra) and r013 expires in a few days.

**Comment by mrribbits** [comment]
We're in the same boat.  Awaiting our Skyra VE11A to be upgraded to VE11C.   So having the VE11A version of r014 would be helpful, as will having the VE11C version soon.

**Comment by eauerbach** [comment]
No versions have been discontinued this cycle...my build process is not exactly automated so I'm uploading them as they are ready.
![dont-panic](https://cloud.githubusercontent.com/assets/1816068/17031838/d2d3e4e8-4f3b-11e6-885d-cee5041edfb7.jpg)

**Comment by ryansangill** [comment]
Thank you! 

My users will be elated when I tell them.

/Ryan

**Comment by mrribbits** [comment]
Great thanks!

**Comment by eauerbach** [comment]
All of the versions are now available.
