### ISSUE TITLE
rc.status doesn't exist on MaRS in VE11A

### ISSUE THREAD

**Issue by lucijj** [CMRR-C2P/MB#129]
I'm trying to install the 10Gb/s NIC into our Skyra's MaRS.  We're using VE11A, and I'm following the instructions provided in the install.txt document in the distribution.

When the MaRS starts, it hangs, and in the init-siemens.log file, there are errors related to the eja_config10GbE.sh file.  A photo of a dumb terminal hooked up to the MaRS is attached here. 
![20160803_155416](https://cloud.githubusercontent.com/assets/5487581/17381901/ec98d7c8-5993-11e6-95e2-4a6cc0f858b2.jpg)

The first error reports that /etc/rc.status is not found.  I searched through the entire filesystem, and rc.status is nowhere to be found.  Of course, without that, rc_reset fails next.  The third error reports that /sbin/lspci is not found.  On my MaRS, I found it in /usr/bin.

I had this working on my VD13 MaRS, but of course, the NIC drivers were built into that kernel, so I didn't need to install them.

I have no idea why the rc.status isn't present, but none of the other init startup files in the /etc/rc.\* directories call it to manage services. ('grep rc.status rc._/_' returns nothing)  The MaRS is using Ubuntu 12.04.3.

Does this make any sense to you?  If you have any insight, I'd appreciate it.

Thanks,
Jeff

**Comment by eauerbach** [comment]
I think you are using an old version of that script that was meant for VB17A. If you use the eja_config10GbE.sh found in the 10GBE_INSTALL_VD13x-VE-LINE folder of the R007 remote server release archive then you shouldn't have this problem.

**Comment by eauerbach** [comment]
Oh, I see the ejaMBRemoteICE-R007.tgz has the wrong script..hold on...

**Comment by eauerbach** [comment]
Please download the new version of the remote recon server [[ejaMBRemoteICE-R008.tgz](http://www.cmrr.umn.edu/multiband/Downloads-RemoteRecon/ejaMBRemoteICE-R008.tgz)], which has been updated to support the new features in the R014 sequences, and use the updated script in the 10GBE_INSTALL_VD13x-VE-LINE folder.

**Comment by lucijj** [comment]
OK, I did all that.  But, there's a different, less specific problem.  I'm going to be out of town for a week, so I can't give you more than another screenshot of the log.  If it's not obvious to you what's wrong, I'll do some more troubleshooting when I'm back, and enlist the help of a slightly more qualified Linux administrator than I am.
![20160803_211817](https://cloud.githubusercontent.com/assets/5487581/17389478/56637ff6-59ca-11e6-9b21-909c1959bc5b.jpg)

**Comment by eauerbach** [comment]
So it is expecting to see the 10GbE adapter as `eth2`. One possibility is that the driver isn't being loaded, another is that the driver is fine but it is being assigned to something other than `eth2`.

If you run `ifconfig -a`, hopefully you will see the 10GbE adapter somewhere. If not, it is either defective or the driver isn't being loaded. I don't have a VE11A system to test, but although I would assume an appropriate driver is preinstalled, it is possible that you might need to install a driver manually. (This wasn't necessary on VD13D.)

If you do find the adapter in the list but it isn't assigned to `eth2`, first try deleting the file `/etc/udev/rules.d/70-persistent-net.rules`, then reboot. Hopefully this will reset the device ordering. Failing that, just edit the script to replace `eth2` with whatever device works.

**Comment by lucijj** [comment]
Sounds good.  I'll try that next week when Im back in the saddle and get back to you.  I happen to have a spare NIC sitting on the shelf, so if all the config stuff points to faulty hardware, I can remedy that pretty quickly.
