### ISSUE TITLE
VE11A R014 BOLD Skyra intensity shift between bands.

### ISSUE THREAD

**Issue by ryansangill** [CMRR-C2P/MB#131]
Hi,
if we split a mosaic and display it in the 3D tool there is a dark stripe between bands (ie slice acc factor == 2 -> one stripe, acc factor == 3 -> two stripes.  Also the average intensity changes from slice to slice within one band (or slice block - not sure of the terminology).
We also had the issue in R013 BOLD whereas we don't see it in diffusion images.
VB17A R014 BOLD on a Trio does not show the problem.
Below is a screen dump from the 3D tool.

Thanks
Ryan

![im-0001-0001](https://cloud.githubusercontent.com/assets/20580727/17552647/75810f16-5f01-11e6-87f7-88031e229e78.jpg)

**Comment by EvelyneBalteau** [comment]
Hi there,

We observe the same effect on our Prisma (VD13D, both with R013 and R014, MB factor = 2).

Has anything progressed on that front?

The difference in intensity decreases when increasing the MB excitation pulse duration.

The screen shot below illustrates what we observed. All images acquired on agar gel spherical phantom with 20-channel head-neck coil, and displayed with identical windowing. To have the effect almost disappearing, one needs to increase quite considerably the RF pulse duration (2560 us is the default duration for an 90° RF pulse).

![intensity_variation_vary_rf_pulse_duration](https://cloud.githubusercontent.com/assets/2632058/19742325/d393f44c-9bc4-11e6-9f5e-aa9377596f79.png)

When decreasing the RF pulse FA, the effect worsens. See below a screenshot illustrating the effect. All images acquired with pulse duration = 2560 us. Windowing different for each image (decreasing SNR). I assume that the MB excitation pulse is optimized for excitation (i.e. FA = 90°) which might explain what we observed, but I still report it in case it would be of any use...

![intensity_variation_vary_rf_pulse_fa](https://cloud.githubusercontent.com/assets/2632058/19742326/d396bf6a-9bc4-11e6-935d-16a398bcd8a4.png)

If you have any recommendation on how to set up the acquisition parameters to avoid this effect, or any progress on the implementation side maybe, please let me know!

Cheers,

Evelyne

**Comment by EvelyneBalteau** [comment]
After a bit of issues-browsing, I guess we're bumping into issue #67 as many other users did before we did...
Why isn't this issue systematically reported in the Application Guide & Release Notes pdf to avoid misusage of the sequence?
In our case, there is no clipped RF pulse issue with MB = 2, FA = 90° and duration = 2560 us (RF voltage still under maximum value) so there is absolutely no warning given when acquiring the data...
Cheers,
Evelyne
