### ISSUE TITLE
Embedded Control in VE11C

### ISSUE THREAD

**Issue by edevita** [CMRR-C2P/MB#133]
Hello,
I was wondering if the default password for Embedded Control in VE11C is known?
We seen to need that to install the MB sequences.
Thank you.

**Comment by eauerbach** [comment]
I'm surprised that Embedded Control is installed on a VE11C system, but if that is the case then you should probably ask service about it.

**Comment by enricogit** [comment]
yes, with some delay we learnt that any site with IDEA license should be given the password of the SYADMIN account (or another suitable account) to enable the 'Update mode' of the Embedded Control System, for sequence installation. Thank you.
