### ISSUE TITLE
Remote recon connectivity

### ISSUE THREAD

**Issue by umm-mrrc** [CMRR-C2P/MB#134]
We are trying to run the remote recon on our Tim Trio MRB17 system, using the recommended Myricom cards installed on both the recon and MRIR computers.  The two Myricom cards are linked directly with a 5m Myricom SFP+ Passive Copper Cable, but neither of the Myricom link lights are on, and the yellow lights just repeat - blink 2x then pause. 

The recon computer is running RHEL 7, and 'sees' the card in the 'Network' configuration as 'MYICOM Ethernet'.  The Myricom is hard coded with an IPv4 address of 10.1.1.3, a netmask of 255.255.255.0, and a gateway of 0.0.0.0.  There are no DNS server or routes defined.  The recon computer firewall is configured to allow tcp port 10000, as well as ssh and vnc-server services.

The MRIR is presumably configured using eja_config10GbE.sh with an IP address of 10.1.1.2, but we have not yet gotten the user/password information from Siemens we need to log on to the MRIR to see or configure anything on that computer.

So, any thoughts would be most appreciated.  Could this be a configuration problem with the MRIR or the recon computer, or should connecting two Myricom cards together at least give a link light regardless of whether they're configured properly?

Thanks,
Steve

**Comment by eauerbach** [comment]
From the host, you can `ssh root@mrir` to log in to the MRIR. `grep eja_config /var/log/boot.msg` should give you an idea if something went wrong configuring the NIC.

**Comment by umm-mrrc** [comment]
Something did seem to go wrong...

mrir:~ # grep eja /var/log/boot.msg
/opt/med/config/scripts/med.rc.0/eja_config10GbE.sh
 (/config/CONFIG_NIC2 does not exist) 2016-09-16 14:09:57 Starting /opt/med/config/scripts/med.rc.0/eja_config10GbE.sh..
.
/opt/med/startup.sh: /opt/med/config/scripts/med.rc.0/eja_config10GbE.sh: /bin/bash^M: bad interpreter: No such file or
directory
mrir:~ #

**Comment by eauerbach** [comment]
Ah, you must have edited eja_config10GbE.sh with Notepad or something which added CRLF line endings. `dos2unix /opt/med/config/scripts/med.rc.0/eja_config10GbE.sh` should fix it.

**Comment by umm-mrrc** [comment]
Again, thanks for the prompt reply.  That did indeed make a difference, but I'm going to have to wait until next week before rebooting to try it again.  Thanks!

**Comment by umm-mrrc** [comment]
That was the problem, and now all is well.  Thank you for the support.
