### ISSUE TITLE
Multi-echo feature in CMRR_MB_EPI_VE11C_R014

### ISSUE THREAD

**Issue by CesarCaballeroGaudes** [CMRR-C2P/MB#138]
Hello,

I'm installing CMRR_MB_EPI_VE11C_R014 and I'd like to use it for multiecho acquisitions. How is it possible to set it up? The instructions indicate that multi-echo support is fully enabled in R014 but I cannot find it in the protocol parameters.

**Comment by eauerbach** [comment]
Contrasts parameter on the Sequence card.
