### ISSUE TITLE
BOLD sequence does not run

### ISSUE THREAD

**Issue by virendram** [CMRR-C2P/MB#141]
Hi.

We just installed CMRR sequence on our 3T Skyra (IDEA: VE11C). But we are having difficulties in getting the sequence to run. I have attached the protocol and the snapshot of the warning. After we got the warning, the sequence just stopped and did nothing. We will appreciate any help regarding solving this matter.

Second, we were planning to do an offline reconstruction but that the option "offline" was not available. Can we use "Aliased" option or we have to use "none" option for offline reconstruction?

Thank you

Regards

VM.

[BOLD_CMRR_sequence.pdf](https://github.com/CMRR-C2P/MB/files/623563/BOLD_CMRR_sequence.pdf)

![bold_runtime_error](https://cloud.githubusercontent.com/assets/8902008/20779517/d4c3b6d8-b729-11e6-81c7-db0e5e4f4ef2.jpg)

**Comment by h-you-man** [comment]
If the sequence stopped after you clicked "OK"?

**Comment by virendram** [comment]
It all runs fine. I had to change the echo spacing to 0.75ms and excite pulse duration to 7000 for a resolution of 2mm3.

Thanks.
