### ISSUE TITLE
>128 slices for fMRI / diffusion

### ISSUE THREAD

**Issue by whitecraine** [CMRR-C2P/MB#143]
Given that our 7T Diffusion data is published with > 128 slices using the slice-multiplier feature, are there plans to release this feature in the C2P? Currently, I'm not able to find/activate it and as such C2P sites are not able to replicate the work we have published.

**Comment by eauerbach** [comment]
I just updated the [Wiki](https://github.com/CMRR-C2P/MB/wiki) with instructions for how to enable this option in the UI.

**Comment by whitecraine** [comment]
Awesome! Thanks so much Eddie!

Joseph

**Comment by whitecraine** [comment]
Hi Eddie,

Is there something similar for the Time shift amount and the diffusion
spoil factor? Those parameters don't seem to be available in the C2P but
are specified in the HCP protocols.

Thanks,
Joseph
