### ISSUE TITLE
Reconstruction problems on VD13D-R014 of Prisma

### ISSUE THREAD

**Issue by Hsiang-Yuan** [CMRR-C2P/MB#145]
Hello, 

We've came across two problems regarding reconstruction.

1. We tried to acquire multiband multiecho BOLD data, the phantom scan was smooth. However, we only got one set of reconstructed images, i.e., first TE at 13 ms. There were no images at other 3 TEs reconstructed. We wonder whether this issue orignated from parameters in settings of sequence, or any other domain, card. 

2. We tried another setting only acquiring multiband BOLD data (MB 6). During the reconstruction, there was small white spots shown on the reconstructed image, as shown in the attached photo. We have no idea how this happened?
![img_1681](https://cloud.githubusercontent.com/assets/24690974/21378951/482a4e8c-c785-11e6-9722-0d5a8f7e4181.JPG)
 
Many thanks for your help

**Comment by eauerbach** [comment]
You should disable the BOLD post-processing. The white dots on the image you show are noisy t-test results superimposed on the image from the BOLD post-processing. Also I would not expect the post-processing to be compatible at all with multi-echo data.
