### ISSUE TITLE
Reconstruction computer will not reboot after R014 installation - scanner down!

### ISSUE THREAD

**Issue by mscohen** [CMRR-C2P/MB#147]
Yesterday we installed R014 on our Prisma fit unit running VE11B. After doing so, the instrument would not come up properly. We received errors from the startup sequence of the reconstruction computer. Thinking that this might be a coincidence, we replaced the recon computer, but the problem persists. We are worried that this may be a problem with the recon codes in the CMRR release. Can anyone help? This is urgent, as our site is now down as a result.

Thank you.

**Comment by eauerbach** [comment]
Thanks for the troubleshooting on this; I added a test in the installer which should hopefully catch this in the future.
