### ISSUE TITLE
Urgent! R015 for VB17A - Installation fails

### ISSUE THREAD

**Issue by pdechen** [CMRR-C2P/MB#150]
Hi,

I just tried to install the latest version on our TIM Trio system. Unfortunately, I get the following error message (see jpg):
![mb-install-error_20170306](https://cloud.githubusercontent.com/assets/26222530/23609616/245b428e-026f-11e7-9972-7c651d1e95d4.JPG)
Am I missing something? I already tried to restart the system before installation.
Do you have any suggestions?

Thanks,
Peter

**Comment by vkemper** [comment]
Hello,
same error here on a VB17A 7T system with the normal and UHF versions. The manual points at encrypted files in the context of NTFS and MacOS, so I thought it might related to this. There was no Mac involved here, and extracting the zip file on a FAT32 formatted USB stick didnt do the trick either.
Valentin

**Comment by eauerbach** [comment]
This was a bug in the installer due to some unexpected small differences between Windows 7 (where I tested) and Windows XP. If you download the zip file again I have updated the installer to correct this.

**Comment by pdechen** [comment]
Great! I downloaded the new version and it worked without any problems.
Thanks a lot,
Peter
