### ISSUE TITLE
[Urgent] R015 for VD13C-SP2 on a Skyra please. R014 is due to expire on 7/3. 

### ISSUE THREAD

**Issue by ZhaolinChen** [CMRR-C2P/MB#151]
Could not find the new R015 for VD13C software. We have a number of projects using this sequence on this software version. We urgently need the new release before the expiry date. Thank you!

**Comment by eauerbach** [comment]
I didn't immediately make versions for VD13C and VD13B in hopes that people were no longer using them... Since you have asked, however, I will make a VD13C version and post it shortly.

**Comment by ZhaolinChen** [comment]
Dear Eddie,

Very appreciated! As we almost all our neuro studies using this MB sequence, future support on this software will be very useful for us. 

Thank you.

Kind regards,
Zhaolin
