### ISSUE TITLE
[R015 for VB17A-Step2.3/F37] Error "2 clipped RF pulses detected"

### ISSUE THREAD

**Issue by WanyongShin** [CMRR-C2P/MB#156]
Dear all
Have you seen this error message at 7T pTX 2.3? the following error message window pops up, and the system hangs up. 

WARNING: 2 clipped RF pulses detected
MBExc[0]:Expected = 60.0[deg];    Actual = 44.5 [deg]
MBexc[1]:Expected = 12.0[deg];    Actual = 8.9 [deg]

Reference amplitude = 111.0 [V]
Max. Transmit amplitude = 169.10[V]

Wanyong

**Comment by eauerbach** [comment]
This means that you are asking e.g. for a 60 degree flip angle, but at maximum transmitter voltage the system can only achieve 44.5 degrees. You will need to increase the RF pulse lengths. If you really really want to disable this message, there is an option described on the wiki page, but this warning is provided with the assumption that you would want to know that you are not going to get the flip angles you requested.
