### ISSUE TITLE
Acquisition time bug R015 on VB17A

### ISSUE THREAD

**Issue by ryansangill** [CMRR-C2P/MB#158]
While trying to determine the time spent on equilibration and calibration shots, we found a funny quirk in the acquisition time estimation. Setting up the protocols attached below we found that if we change from no in-plane acceleration to GRAPPA iPAT 2 AT is estimated to be 1:00 whereas if we select iPAT 3 and then iPAT 2 AT is estimated to be 0:52.  It is possible to save the protocol with either estimate but the scan clock always counts down from 1:00.
I imported the protocols in a Skyra (VE11C) and could not replicate the issue.

Best regards

Ryan

[MBTEST.edx.zip](https://github.com/CMRR-C2P/MB/files/857450/MBTEST.edx.zip)

**Comment by eauerbach** [comment]
Also the time estimation breaks when switching between reference scan modes. It seems to be generally correct for the GRE/FLEET modes, but breaks for segmented.

**Comment by eauerbach** [comment]
I believe these issues are fixed since R016
