### ISSUE TITLE
Skyra VE11C - Preparation of image reconstruction failed

### ISSUE THREAD

**Issue by jirikeller** [CMRR-C2P/MB#159]
Hi, 
 I just installed an upgraded Multiband and as we are on VE11C, we had to request a trial for SMS EPI from Siemens. Their SMS sequence runs, but I am not able to launch any of our multiband sequences. I did a savelog procedure, but I am not sure what exactly may help.  Sequence tunes for a while and crashes with "Preparation of image reconstruction failed" error.

After encountering this problem, I re-installed again the sequence with full machine powercycle, but this did not help.

**Comment by jirikeller** [comment]
Based on hint of @michalmikl i digged into eja_checkNVIDIA.sh script and found out, that a symlink /usr/lib/libcuda.so.1 which should be pointing to /opt/medcom/MRiCustomer/ice/libcuda.so.319.37.eja points to /opt/med/lib/libcuda.so.319.37.eja (which does not exists). After erasing this broken symlink and recreating (after ssh root@mars) sequence runs without any problems. I am just wondering if this modification survives scanner reboot or some other action is needed ? I'll (not) see it hopefully after machine/mars restart ...

![fix](https://cloud.githubusercontent.com/assets/1626746/24301410/d0a7f1f6-10af-11e7-98c4-eccd62720d4b.png)

Copy-paste:

cmd
ssh root@mars
cd /usr/lib
mv libcuda.so.1 libcuda.so.1-broken
ln -s /opt/medcom/MRiCustomer/ice/libcuda.so.319.37.eja libcuda.so.1

**Comment by jirikeller** [comment]
Update: we were finally able to do a full power cycle of the magnet and YEAH, the changes ARE permanent. So, this issue can be closed and marked as solved (for people encountering the same problém).

**Comment by eauerbach** [comment]
Hmm, were you previously running VE11A or VE11B before upgrading to VE11C?

**Comment by eauerbach** [comment]
and I assume your MaRS does not have a GPU?

**Comment by jirikeller** [comment]
Actually, we were upgrading from VD series and we did not get new imager nor CUDA-capable GPUs (there is a GPU, but without support for computations).
