### ISSUE TITLE
Issues with readCMRRPhysio.m 

### ISSUE THREAD

**Issue by michalmikl** [CMRR-C2P/MB#161]
Hello everybody,

I tried to use readCMRRPhysio.m matlab script to read the physological recording from DICOM files (as a new feature in R015 release of CMRR MB-EPI BOLD sequence). And found two issues.
1) There is (probably) bug on the line no. 192. 
 _if ((1 == exist('PULS', 'var')) && ~isempty(PULS) && nnz(PULS))    , physio.PULS = PULS;     end_
should be changed to
 _if ((1 == exist('RESP', 'var')) && ~isempty(PULS) && nnz(PULS))    , physio.PULS = PULS;     end_

2) The script return error on the line no. 317 for data with two or more echoes
  _if (arr(:,curvol,curslc)), error('Received duplicate timing data for vol%d slc%d!', curvol, curslc); end_
Therefore, the script cannot be used for multiecho data without modification. I tried to use very simple modification 
 if ~(arr(:,curvol,curslc));  arr(:,curvol,curslc) = [curstart curfinish]; end
which save only the values for first appearence of specific volume and slice number (the first TE readout).

Best regards,
Michal

**Comment by eauerbach** [comment]
should be fixed in the updated version 53d8bb58306195eed423ed5dfab618774dd1f466
