### ISSUE TITLE
Feature Suggestion: RF-phase correction for MB Phase images

### ISSUE THREAD

**Issue by buchsy** [CMRR-C2P/MB#167]
Dear all,

This message is a feature suggestion/correction step for the MB-EPI sequence.

I have been looking into the phase images acquired using MB EPI and I noticed an inconsistent phase in slice select direction due to a global shift added for each band. We found out that for minimizing RF peak power, and hence for minimizing SAR, the sequence uses the MB RF phase scramble option (Proc. ISMRM 2012, #2209) (This information is also included in the release notes); and after performing this step, each band has a respective phase offset as defined in the abstract.
In order to correct the phase, one just needs to use these RF phase values from the abstract. Make sure to check whether 'MB RF phase scramble' option was ON. This will only work if the option was ON.

Here is an example for phase correction:

![image](https://cloud.githubusercontent.com/assets/28162433/26164748/96c8c8ea-3afb-11e7-9df9-4ab44e565fc3.png)

The images shown here are in sagittal view, demonstrating the band specific phase offset correction. The data was collected with MB factors = 3, 4 and 5, all with 60 slices and fixed TE/TR/BW/voxel resolution on a 7T Siemens scanner.

Please note that when the correction was performed, the values were used with an opposite polarity (sign), i.e. the RF phase values, presented in the above mentioned abstract, were added instead of subtraction to get a homogeneous realistic phase profile. 

It is a very simple step and hopefully, this message could be helpful to anyone who wants to study MB-EPI phase. 

This phase correction feature could also be added in the phase processing functor for the future releases. QSM and phase imaging has been a strong research field in many clinical studies; and the MB-EPI phase has a potential to become an integral part of it.

Thanks,

-Sagar Buch
Western University, London, Canada

**Comment by eauerbach** [comment]
I think this issue is resolved in the upcoming C2P; going forward the "officially supported" solution for all types of phase imaging is to use the SENSE1 coil combination option. In this case this phase should be accounted for.
