### ISSUE TITLE
availability on VE11P software 

### ISSUE THREAD

**Issue by ZhaolinChen** [CMRR-C2P/MB#168]
Hi,

Could you make the multiband EPI C2P available on VE11P software platform for Biograph mMR? I could not find a download link for VE11P...

Thanks,
Zhaolin

**Comment by eauerbach** [comment]
VE11P and VE11R (Terra) versions are being worked on and should be available soon.

**Comment by ZhaolinChen** [comment]
Dear colleagues,

I am wondering if the VE11P is available now or when it can become available? We have just got our Biograph upgraded to VE11P software, and several projects are currently waiting on this Multiband C2P. 

Thank you.

Kind regards,
Zhaolin

**Comment by eauerbach** [comment]
It is available now: [Release R015a for VE11P](http://www.cmrr.umn.edu/multiband/Downloads-Seq/CMRR_MB_EPI_VE11P_R015a.zip)

**Comment by ZhaolinChen** [comment]
Great Thanks Eddie.

Kind regards,
Zhaolin
