### ISSUE TITLE
phase encoding direction change

### ISSUE THREAD

**Issue by scannexus** [CMRR-C2P/MB#169]
We have noticed several times within CMRR MB  using copy references, copy center of slices, the PE direction changes from AP to LR. PE direction should have stayed the same after copying the center of slices. Our MB version used is R015a, but we also noticed this in previous versions. MB is used at Prisma fit, VE11 and 7T Magnetom, VB17.
Does anyone know how this can happen?

**Comment by eauerbach** [comment]
Are you typically selecting the "Copy phase encoding direction" checkbox when using the Copy Parameter option?

**Comment by scannexus** [comment]
No, we do not select the copy phase encoding direction checkbox. Only copy center of slices and/or adjustment volume box.

**Comment by jpyles** [comment]
@scannexus We have had that same issue, but I believe it is a general Siemens bug with copy and pasting references and not multiband specific. Perhaps others have difference experiences though. It does not seem to happen every time, and seems worse if you are using PA phase encoding (meaning more likely to either switch back to AP or to LR on copy). 

We're on a Verio running VB17A.

**Comment by scannexus** [comment]
Thanks for your reply. It seems you have the same issue. I was wondering myself if it is a general Siemens bug or a MB issue. It does not happen every time as you described. We are also on VB17A.

**Comment by julfou81** [comment]
Hi, 
It is a general issue for Siemens sequence each time you copy parameters involving the encoding direction. If the target sequence for which you want to change parameters has an encoding direction range (AP, PA, RL or LR) different than that the reference scan, the target sequence will be changed to a different direction that the one you are aiming at.
Exemple: reference scan in AP (orientation : 0°)
target scan in AP(-45° < rotation < +45°) ->  AP (0°) after copy, good 
target scan in RL (45,01° < rotation < 134,99° ) -> RL (90°) after copy, bad!
target scan in PA( 135° < rotation < 135° ) -> RL (90°) after copy, bad!
target scan in LR (- 45,01° < rotation < -134,99° ) -> RL (90°) , bad!

That is why the option: "Invert RO/PE polarity" (in Sequence/Special tab)  is interesting if you want to set up a protocole with 2 sequences of opposed phase encoding directions (for popup for instance), you keep the same "official phase encoding direction" (from the "routine" tab) for both sequences, however, thanks to this parameters, your 2 sequences will play with opposed phase direction and your protocol is not messed up by Siemens wrong behavior when you copy/paste parameters from one sequence to another.
