### ISSUE TITLE
completely periodic MB possible for simultaneous EEG/fMRI?

### ISSUE THREAD

**Issue by fredcito** [CMRR-C2P/MB#171]
Dear Eddie et al,

One of our groups is doing simultaneous EEG/fMRI, which would serious benefit from MB acceleration. Typically we use a completely periodic EPI sequence (no little hiccup at beginning of each TR) because it is much easier to eliminate the scanner-related artifacts in the EEG signal. Is it possible for us to tweak the CMRR MB parameters to do the same?  

best
Fred

**Comment by eauerbach** [comment]
Yes, the option "Disable freq. update" on the Sequence/Special card is provided for this purpose.

**Comment by fredcito** [comment]
Ah thank you very much Eddie


On 30 August 2017 at 22:00:09, Eddie Auerbach (notifications@github.com) wrote:

Yes, the option "Disable freq. update" on the Sequence/Special card is provided for this purpose.
