### ISSUE TITLE
Remote Recon Not Working with Step5 Imager on Verio VB17A

### ISSUE THREAD

**Issue by jpyles** [CMRR-C2P/MB#173]
We have just done a "hardware only" Evolve upgrade on our Verio running VB17A. First the host was replaced with a new HP and we ran fine for a week with the multiband remote reconstruction setup with our old Step4 imager and the setup we had been using (Myricom 10G-PCIE-8B-S card with remote recon GPU directly connected by fiber).

Today we installed a Step5 imager. Multiband worked fine in initial tests so we installed the Myricom card to test remote recon. That resulted in a PCI-RX Receiver and recon failure error (see below). We took the Myricom card out and were back to where we started with everything working fine but no remote recon.

```
E  11-Oct-17 13:24:48	10	MRI_COS           0   Preparation of image reconstruction failed. System might be busy. Please retry measurement, if not successful restart syngo MR.    
---------------------
E  11-Oct-17 13:24:48	8	MRI_PRC           0   Image reconstruction failed. MeasUid    30.    
---------------------
E  11-Oct-17 13:24:48	8	MRI_PRC           1   Image reconstruction failed. MeasUid    30.    
E  11-Oct-17 13:24:48	1	MRI_IRI           0   There is a problem with the PCI-RX Receiver. Please retry measurement. Please call service if the problem persists.     
---------------------
E  11-Oct-17 13:24:48	1	MRI_IRI           1   There is a problem with the PCI-RX Receiver. Please retry measurement. Please call service if the problem persists.     
E  11-Oct-17 13:24:48	6	MRI_RFS           0   No patient registered.    
---------------------
E  11-Oct-17 13:07:37	34	MRI_PER           0   Scanner is booting.   
```

We are now trying to configure remote recon over the extra 1GbE in our Step5. However we are having no luck with that either. `ip link show` only displays eth0. 

The `eja_config10GbE.sh` script we are using makes no mention of a Step5 imager. So maybe this is the problem? The Step5 also appears to have two spare ethernet ports: on on the upper left above the keyboard serial port, one just to the left of the local ethernet connection. We get green lights for the upper left port, no lights when we plug a cable into the port to the left of the port where the local connection is plugged in.

Any help solving either of these issues would be much appreciated! 

*Update 10/12/17:* We have replicated the problem again by removing the 10GbE card, running the scanner fine, and then re-installing and the error coming back. 

@eauerbach : We can send you a link to a save log as well as the `eja_config10GbE.sh` script we are using if that would be helpful. Many thanks!

**Comment by eauerbach** [comment]
Is there more than one empty PCIe slot in the Step5? I have never seen one myself. I do know that Siemens is using a particular motherboard in some of their systems that has strange issues that depend on the arrangement of cards in the slots (interrupt assignment/conflicts). We "solved" one problem by swapping cards between slot 1 to slot 2, and another by installing the latest BIOS update.

Another possibility would be to try a different card. Intel X520-SR1 should be a drop-in replacement for the Myricom and may work better with the Step5 (for whatever reason). But if that isn't feasible, and the slot swapping and/or BIOS update don't work, let me know and I can see if there is an updated Myricom driver available.

**Comment by jpyles** [comment]
@eauerbach Thanks so much for the reply! There is only one PCIe slot in the Step5, so not possible to switch. An interrupt conflict of some sort sounds possible. We can communicate with the Myricom when it is installed, it is just that the scanner does not seem to like it there and won't scan, throwing the PCI-RX Receiver error. 

If you have an updated Myricom driver that would probably be the easiest thing to try first. Otherwise we can try to get an Intel X520-SR1. 

Updating the BIOS is something we would probably need to do with Siemens supervision I think? 

Thanks again!

**Comment by eauerbach** [comment]
The BIOS update would have to come from Siemens; they used a modified custom BIOS. You would have to ask your local service engineer to get the latest BIOS CD and update the imager. It is possible that you already have the latest version, I don't know.
