### ISSUE TITLE
dicom header field key? Looking for LeakBlock, PrescanNormalize on or off.

### ISSUE THREAD

**Issue by jaetzel** [CMRR-C2P/MB#174]
I have fMRI images collected on a Siemens Prisma, CMRR multiband releases R014 and R015. I would like to confirm whether LeakBlock and PrescanNormalize was on or off for some of these images. I believe these options may be coded in the dicom header, perhaps a WipMemBlock field? However, these fields are coded by number. Is there a key for which dicom header field corresponds to LeakBlock and PrescanNormalize?

thanks!
Jo

**Comment by eauerbach** [comment]
In the DICOM images, LeakBlock will be indicated in the ImageComment field with the MB factor and the CAIPIRINHA (PE) shift, e.g. "Unaliased MB4/PE3/LB".

Prescan Normalize is a bit more difficult; ImageType will include NORM if any kind of normalization is enabled, but you have to go into the shadow header to narrow down the exact type of normalization used (e.g. image shadow field "ImageHistory" containing "NormalizeAlgo:PreScan").
