### ISSUE TITLE
Strange Behavior of FOV Phase

### ISSUE THREAD

**Issue by jspielb2** [CMRR-C2P/MB#175]
We've noticed some strange behavior of the FOV phase field in all the MB sequences.  Specifically, it defaults to 100%, but when we click on that field and then click somewhere else, the value changes to be <100% (e.g., 92.3%, but the particular # seems to depend on other settings).  After this change, we are unable to set it back to 100% (e.g., options are 92.3 or 103.8).  However, if we don't touch the field, we are able to run fine with FOV phase=100%, so 100% doesn't seem to be a problematic setting itself (at least, we hope not).  

To try to identify where the problem is coming from, I started over with the out-of-the-box-settings, which didn’t show the strange behavior.  The problem started to occur after changing the base resolution to be anything but 128 or 126 (leaving all other settings as the defaults).  

We are running on a Prisma with the VE11C R015a release.  Happy to send along a screen shot and/or printout if it's helpful.  

Best,
Jeff

**Comment by eauerbach** [comment]
I believe we have this figured out and it will be fixed in the next release.
