### ISSUE TITLE
Slice order interleaved mistake in documentation

### ISSUE THREAD

**Issue by lrq3000** [CMRR-C2P/MB#176]
There is I think a mistake about the slice order interleave in the following documentation (point 2.2.1):

https://wiki.humanconnectome.org/download/attachments/40534057/CMRR_MB_Slice_Order.pdf?version=2&modificationDate=1386950067494&api=v2

Indeed in the documentation it is specified that an odd number of slices will make the slice order interleave start with the first even slice (0 or 2), and an even number of slices will make the slice order interleave start with the first odd slice (1).

However, in the Siemens documentation, it is specified the opposite: an even number of slices will have an even-first interleave acquisition, and an odd number of slices will have an odd-first interleave acquisition:

https://web.archive.org/web/20171016190224/https://www.healthcare.siemens.com/siemens_hwem-hwem_ssxa_websites-context-root/wcm/idc/groups/public/@global/@imaging/@mri/documents/download/mdaz/nzmy/~edisp/mri_60_graessner-01646277.pdf

**Comment by eauerbach** [comment]
Both documents are correct, but the Siemens white paper starts numbering slices with #1, whereas the CMRR/HCP document starts with #0. So what you are considering an "even numbered slice" vs. an "odd numbered slice" is swapped between the two documents.

Odd number of slices: first anatomic slice first (CMRR slice #0; Siemens slice #1)
Even number of slices: second anatomic slice first (CMRR slice #1; Siemens slice #2)

**Comment by lrq3000** [comment]
Ok thank you for the clarification, so it means that CMRR starts at 0-index whereas Siemens usually use 1-indexing just like MATLAB.

I think it would be nice to clarify this somewhere in the document, as the document states only the Siemens behavior, but the numbering convention is different here.
