### ISSUE TITLE
Failure to Prepare Reconstruction VE11C - R015a - Siemens Skyra

### ISSUE THREAD

**Issue by bedepue** [CMRR-C2P/MB#177]
Hi Eddie-
I emailed awhile back concerning the MB acceleration factor (support request #172) and other options not showing up after upgrading to VE11C and then installing R015a on a Skyra. You suggested that it was likely due to the SMS license not being installed.

Siemens has installed the SMS license, but unfortunately I keep getting the same failure to prepare reconstruction. Full shut down and restart. I attach an images of the error.

![image1](https://user-images.githubusercontent.com/32045688/32302181-c3e42cc8-bf37-11e7-8bdf-4eef02e9eff2.jpeg)

I know our MARS computer has no GPU, but is the latest 720 or 740 model. I also looked through the logs, but found nothing. I imagine it really doesn’t have to do with reconstruction, as it doesn’t even start the scan or even if MB acc factor = 1. I tried the fix that someone else had posted about a broken symlink in support request #159. However, I assume that  the updated R015a fixed this issue, because no symlink was found.

I am not sure if it’s an installation problem, when I start the CMRR installer (.exe) it flashes and then nothing (Embedded control off), perhaps because it’s already installed? I can’t find a way to uninstall and reinstall, however I’m not sure if that would help anyway.

Any info is appreciated. Thanks,
Brendan

**Comment by eauerbach** [comment]
If the installer just flashes and nothing happens, something is wrong with the installation files. I would suggest following this procedure:

1) download again the VE11C installer .zip file
2) copy the .zip file onto a flash drive
3) on the scanner, disable embedded control
4) copy the .zip file to C:\Temp on the scanner
5) right click on the .zip file, select "Extract All..."
6) extract to somewhere under C:\Temp, e.g. C:\Temp\CMRR_MB
7) double-click on C:\Temp\CMRR_MB\INSTALL_CMRR_MB_EPI.exe

The main point is to copy the .zip file to the scanner and extract it there, to avoid any missing files, corruption, or strange permissions being assigned as a result of extracting on another computer.

If this procedure still fails with the installer flashing and nothing else happening, then launch a Command Prompt window and execute INSTALL_CMRR_MB_EPI.exe from there. Hopefully in that case you will see an error message in the window.

Finally, if the installer succeeds and you still have image reconstruction errors, then perhaps it is an unexpected issue with your system (maybe your MaRS is a new model with an unusual configuration I am not expecting). In that case, when you see the error, collect a savelog and send it to me.

**Comment by bedepue** [comment]
Twas an installer problem. All is fine now. Thanks so much for your help.
