### ISSUE TITLE
Issue with license file release R016 (VD13D)

### ISSUE THREAD

**Issue by MRC-CBSU** [CMRR-C2P/MB#179]
After installation on the scanner, we get the following error message:

The C2P license file <cmrr_mbep2d_license.lic> is invalid (code 7)! Please install a valid license using the installer program included with the distribution archive. 

The license file is present in seq folder, and the installer was used for the installation, so not really sure what else to try. Any advice would be greatly appreciated. 

Thanks, 
Marta

**Comment by kisboard** [comment]
Same issue on VB19A Verio system in Korea.

**Comment by FGrouiller** [comment]
We have also the same issue on VB17A with a Trio.

**Comment by MarkusBarth** [comment]
We have the same here on VB17 for 7T. Rebooting the scanner did not solve the issue.
As a workaround we manually reinstalled the older version (15) as the installer script would not work.

**Comment by YuvalPorat** [comment]
We have the same problem on VD13A / Skyra.... currently trying to reinstall the previous version

**Comment by kuuseli** [comment]
Same issue with VB19A on a Verio in Finland. Tried to install it twice - no problems with the install, but gives and error message when we try to scan. Re-installed the old version and it's working.

**Comment by eauerbach** [comment]
Sorry about this. Is everyone using systems with the locale set to something other than US English?

**Comment by MRC-CBSU** [comment]
Ours is in UK English.

**Comment by claus-magdeburg** [comment]
Same problem at the Prisma in Magdeburg. That system is set to a German local environment.

**Comment by eauerbach** [comment]
Ok, I figured out the problem. I tested mainly on VE11C and in the end had to make a small change for VB17A/WinXP compatibility; rather unexpectedly this worked perfectly on the simulator but broke everything on the scanner. Very unusual. Anyway, I will upload updated fixed versions to the web site shortly.

**Comment by markymarkymark** [comment]
Same issue here with our VD13D Prisma. Our locale is US English.

**Comment by eauerbach** [comment]
The updated/fixed sequences have been posted on the web site. Please let me know if there are still any problems.

**Comment by kisboard** [comment]
Dear Eauerbach,

Thanks a lot.
1st testing on VE11C Prisma is working well with US english locale, in Korea.

Other version installation results will be updated.
Have a good day.

**Comment by kisboard** [comment]
VE11A Skyra works well. Thank you.

**Comment by MarkusBarth** [comment]
Works on VB17 7T and Prisma VE11C. Thanks Eddie!

**Comment by kuuseli** [comment]
Unfortunately not working on the Verio 3T VB19A in Finland. Same issue and no errors occurred during the install.

**Comment by kisboard** [comment]
Hi, Kuuseli,

I also installed MB EPI on VB19A Verio, today. It works well. If you downloaded the sequence few days ago, then try to install with new download. yesterday, fixed version was uploaded.

Thanks. have a good day.

**Comment by kuuseli** [comment]
Reinstalled and now it works. (Siemens 3T Verio in Finland). Thank you!

**Comment by YuvalPorat** [comment]
Reinstalled the new version on Skyra VD13A with English UK and all is well :-) Thank you!!

**Comment by MRC-CBSU** [comment]
All good for our VD13D Prisma now as well, thanks Eddie for sorting this out.
