### ISSUE TITLE
Image recon problem with R016 on VE11B Prisma

### ISSUE THREAD

**Issue by swrieger** [CMRR-C2P/MB#181]
Dear all,

Having just installed R016 (downloaded yesterday, after the fix for the licence issue), I get the error "Pipeline preparation failed: Composer Error in Protocol Access Service". I have gone back and forth a couple of times between R015 and R016, and it's always the same. R015 works fine, R016 gives the error. Any ideas what the problem might be? I have a savelog I can send you if that would help.

Cheers
Seb

**Comment by eauerbach** [comment]
Please send the savelog and I will look at it.

**Comment by swrieger** [comment]
I have sent it via our large file service to eja@..., I hope that's ok.

**Comment by eauerbach** [comment]
I can't determine why, but somehow the R015 ICE program was being loaded on the MaRS while the R016 sequences and ICE were on the host. Usually this would mean that the MaRS wasn't rebooted during the installation, but it looks like it was. Could you try installing R016 then fully power cycling the system?

**Comment by swrieger** [comment]
That seems to have done the trick! I guess I could have tried that to start with, but it hadn't occurred to me as the MaRS was definitely rebooted every time I ran the installer.
Thank you again for your help!
