### ISSUE TITLE
VB17A R16 - FLEET recon crash with "Invert RO/PE poloarity" checked

### ISSUE THREAD

**Issue by benediktposer** [CMRR-C2P/MB#183]
Image reconstruction crashes when checking the special card tickbox for gradient reversal.
this appears to be independent of 
- number reference lines
- grappa factor 2 or 3
- A-P or L-R PE 
- whether or not SB image output is selected

See MrParcTraceSrv.log attached, it's a SODA issue.

**NB!** All fine when manually applying a 180 degree FOV rotation (i.e P-A phase encoding)

[ICE.log](https://github.com/CMRR-C2P/MB/files/1528880/ICE.log)

**Comment by xjqian** [comment]
confirm this issue for VB17A R16 eja_ep2d_se as well on 7T.

**Comment by eauerbach** [comment]
Will be fixed in the next bugfix release (I had done all of the "hard work" to address this issue already, but neglected one line to enable it)

**Comment by eauerbach** [comment]
R016a is released and fixes this issue.
