### ISSUE TITLE
VB17A R16 - FLEET refscans resetting to Segemented when changing GRAPPA factor

### ISSUE THREAD

**Issue by benediktposer** [CMRR-C2P/MB#184]
not really an "issue" for attentive users, but for completeness:  I observed that when FLEET refscans is selected, and the GRAPPA factor changed, the refscan mode 'silently' resets itself to Segmented

**Comment by eauerbach** [comment]
Thanks, this one will be fixed in the next bugfix release

**Comment by eauerbach** [comment]
R016a is released and fixes this issue.
