### ISSUE TITLE
image reconstruction failure for DTI protocol with R016 VE11A and SENSE 1 Coil combine ON

### ISSUE THREAD

**Issue by CatherineMorganII** [CMRR-C2P/MB#187]
This issue has actually been resolved, but posting here in case helps anyone else. We have a couple of different research projects using this C2P for DTI, but for one of them the scan would stop after 5-10 seconds with image reconstruction failure message.

Our techs tracked it down to the below:

Sequence>Specials card 

SENSE 1 Coil combine: Change from on to off.

Release 016 notes say: "The sense 1 coil combination option now properly supports the calculation of phase images. This is the only recommended scheme for acquiring phase images with multichannel receive coils."

for all DTI protocols with it turned off they ran fine, but with it on (which we didn't need it to be, and not sure how it defaulted to be on with the R016 license and sequence update) the image reconstruction fails.

**Comment by tknows20** [comment]
We faced the same issue when setting up a project to use the protocol similar to that for the Phase 1b HCP Lifespan protocol. We downloaded the .edx version to use on the PRISMA scanner protocols.humanconnectome.org/CCF/

As described above, the diffusion scans would stop after 5-10 seconds w image recon failure message.  We tracked it to SENSE 1 Coil combine on vs off. 

We would prefer for the SENSE 1 Coil Combine to be on. Just wondering if anybody has a workaround for this? 

Thank you!

**Comment by eauerbach** [comment]
We use SENSE1 routinely on multiple systems without issue as far as I am aware, and I personally am unable to reproduce this problem. If you collect a savelog after you see the error and send it to me I can investigate. Please make sure you are using the latest version R016a dated December 19.

**Comment by tknows20** [comment]
Indeed the SENSE1 worked fine after we downloaded the R016a, and the recon worked ok.
Sorry for the trouble!!

Much thanks!!
