### ISSUE TITLE
Recon failures with R016 under VE11C

### ISSUE THREAD

**Issue by mharms** [CMRR-C2P/MB#188]
Hi Eddie,
I'm getting multiple reports of recon failures, or inability to start the sequence, with the cmrr_ep2d_bold.  These failures are currently somewhat sporadic, as rebooting the scanner seems to restore functionality, but the problem keeps returning.  We are using "Release R016 for VE11C", with a build date of 27-Nov-2017.

We haven't had a chance yet to see if get the same failures on our other VE11C Prisma, so I guess in principle that there might be some other hardware issue.  But given that these failures started after our switch to the R016 version, and that others have reported seemingly related issues, a bug in R016 seems possible.

Would a save log be helpful, or do you already have what you need from another site?

thanks,
-MH

**Comment by KhallilTC** [comment]
Hi Everyone,

I had the same problem right now, running VB17A @ Magneton 7T

Thanks,

**Comment by mharms** [comment]
Update: We've since lost all communication from the host to the MARS.  Siemens engineer is planning on replacing the MARS tomorrow morning.  So, it appears that these particular MB scan problems were a harbinger of a broader MARS hardware problem.

**Comment by eauerbach** [comment]
Please send me a savelog if it continues. Sounds like a MaRS problem, though. Either the MaRS or connectivity to the MaRS. I don't suppose you have a KinetiCor camera on that system...

**Comment by mharms** [comment]
No reported problems since our MARS replacement, so you can close this Issue.  Sorry for the false alarm -- just an unfortunate coincidence of our MARS starting to go bad after the upgrade to the R016 release.  (Interestingly though, the initial problems _were_ specific to the CMRR sequences.  Perhaps the GPU, or communication with the GPU was starting to go bad...?)
