### ISSUE TITLE
license for physiological file read-in

### ISSUE THREAD

**Issue by SaskiaBollmann** [CMRR-C2P/MB#197]
Hi Eddie,

do you have a license under which your code is released? We would like to integrate your extractCMRR.m functionality into the [physIO toolbox](https://www.tnu.ethz.ch/de/software/tapas/documentations/physio-toolbox.html) to allow the read-in of dicom files.

On another note, do you know how the HCP physiological files are pre-processed? Somehow, the files that are available don't match the [description](https://wiki.humanconnectome.org/display/PublicData/Understanding+Timing+Information+in+HCP+Physiological+Monitoring+Files) nor the default output from the CMRR sequence, but look very similar to your readCMRRPhysio output. Any info on that would be very much appreciated.

Kind regards,
Saskia  Bollmann

**Comment by eauerbach** [comment]
I added a license..

The old HCP physiological files should use the default output of the Siemens PMU. If they have been processed and don't match the description you linked to then I really have no idea. That would be best asked perhaps on the [HCP-Users](https://www.humanconnectome.org/contact-us) mailing list.
