### ISSUE TITLE
Increased helium boil-off due to MB-EPI?

### ISSUE THREAD

**Issue by schlinde** [CMRR-C2P/MB#202]
Dear all,

we are running the latest versions of the CMRR sequences on a Siemens Skyra with a 64-channel head and neck coil with MB factor 4-8 for functional imaging (FA45-52, TR 700-1200ms, voxel-size 2.5mm isotropic in most cases). On days of heavy usage (3-7 subjects with 3-4 15 minute fMRI sessions in a row) the system seems to show an increased helium boil-off compared to standard clinical usage. Does anybody else have similar experiences? Please give us your feedback to help us get to the bottom of the problem.

Thanks a lot
Peter zu Eulenburg

**Comment by xjqian** [comment]
We've had that experience on our Skyra. A bit more helium boil-off than standard clinical usage is normal. However if the helium boil-off is a lot more, then that indicates a cold-head hardware or installation issue exacerbated by the heavy usage of high duty cycle EPI protocol.

**Comment by schlinde** [comment]
Thanks for your quick response. Will talk with our radiology department about. You confirmed by feelings of the matter.
