### ISSUE TITLE
Cannot print/create protocol PDF from scanner after R016 release

### ISSUE THREAD

**Issue by TerynWilkes** [CMRR-C2P/MB#203]
Hello everyone,

We have a Siemens Prisma running VE11B software here at University of Colorado Boulder, after R016 (released 11/20/2017 and installed on our system 12/3/2017) we can no longer create PDF's of protocols containing CMRR MB base sequences. Any Siemens standard sequences, as well as other WiPs, appear in the PDF as normal. We have done a lot of troubleshooting with Siemens engineers, including creating a VM of our system prior to the R016 update, and we were just told that is the likely cause.

Has anyone else experienced this? At least for our researchers this has become a significant issue and we have been unable to find a workaround. 

Thank you for any help.
Teryn

**Comment by BenInglis** [comment]
Suggest you try R016a (build date of 19Dec2017) next. Might be an old rev issue.

Cheers!

**Comment by TerynWilkes** [comment]
Thanks! Our physicist, located at a different site, usually provides us with the needed CMRR updates so I can ask him for R016A, just confirming that release is approved for VE11B?

**Comment by BenInglis** [comment]
Yep, R016a is current for all versions of SyngoMR. Please see: https://www.cmrr.umn.edu/multiband/

**Comment by TerynWilkes** [comment]
Excellent, thank you for your help! Previously we have not needed to update the license prior to its expiration of 6-9 months, I wasn't aware a new version was even available yet.

**Comment by BenInglis** [comment]
If you still have a problem, try "Show unlicensed items" in the Exam Explorer menu. You might have another expired WIP or C2P sequence hidden away in your protocols coincidentally.

**Comment by eauerbach** [comment]
This was fixed in R016a, but there is also a workaround described here: #186

**Comment by TerynWilkes** [comment]
Thank you, I had checked for that already and didn't see anything else of concern. I'll request the R016a version and update after it's installed.
