### ISSUE TITLE
Installation errors- VE11C - MB R016

### ISSUE THREAD

**Issue by andregouws** [CMRR-C2P/MB#206]
Hi,

We are having some problems installing the MB (and spectro actaully) packages on our Prisma 3T. 

We follow the instructions and everything appears to work (including logging in as adv user, running the Embedded Control interface) .. the installer appears to put all the .dll and .so files in the correct directories (c:\Medcom\MriCustomer\seq), and the ice folders are set up correctly also. 

The problem is that the sequences never appear in the dot cockpit interface. We have traced back through the logs and found the follow PAS exception error message in syngo.MR.ExamDb.Server.Log (log extract attached) .. 
[syngo.MRI_ExamDb.Server.log](https://github.com/CMRR-C2P/MB/files/1932138/syngo.MRI_ExamDb.Server.log)

For completeness, we are running the following software versions / patches --

COEM VZ10F_SL02P02
syngo VH22B_SL19P26_CSI03
N4_VE11C_LATEST_20160120
SecurityUpdate_SU28_F2 (SU28)
N4_VE11C_LATEST_20160120_P16 (SP01)
N4_VE11C_FEATURE_20160120_SD04_F1 (SD04)
N4_VE11C_FEATURE_20170704_SH03_F2 (SH03)

Any help would be greatly appreciated. Thanks for your time.

Andre'

**Comment by andregouws** [comment]
I should add that we currently have a Siemens SMS product trial license installed.

**Comment by eauerbach** [comment]
You need the IDEA license installed on the scanner.

**Comment by andregouws** [comment]
Trivial when you know how I guess ... Thanks!

**Comment by andregouws** [comment]
Solved by installing IDEA license (Siemens said they had done this months ago but turns out they hadn't).
