### ISSUE TITLE
Single BOLD run 4096 volume limit?

### ISSUE THREAD

**Issue by dfabbott** [CMRR-C2P/MB#209]
Using CMRR_MB_EPI_VE11A_R016, on a Skyra, trying to prescribe 1hr BOLD fMRI acquisition with multiband factor 6, TR=0.504s (3mm isotropic) or TR=0.761s (2mm isotropic), but can’t seem to set up the acquisition to acquire more than 4096 volumes (about 35 mins or 52 mins respectively). Why? Is this a limitation of the Siemens platform or of the CMRR sequence? Any way around it (prefer not to have to acquire 2 separate runs)? 
Thanks,
David.

**Comment by dfabbott** [comment]
Hi Eddie, 
It would be great if this issue could be fixed. I have discovered that the impact is three times worse when doing multi-echo because the three images saved for each TR count towards the limit, so effectively can only get up to 1365 TRs per run, which is way short of what we need in our application.
Many thanks,
David.

**Comment by eauerbach** [comment]
I will look into it. Adding an option to split each echo out into a separate series may be a solution.

**Comment by eauerbach** [comment]
I can't reproduce the issue with multi-echo. I can acquire 4096 repetitions with 3 echoes and everything is fine, resulting in 12288 images. Perhaps it is an issue with VE11A (I tested on VE11C), or do you have some post processing options enabled on the BOLD card?

**Comment by dfabbott** [comment]
We are also on VE11C, and the 'GLM Statistics' option was enabled. Disabling it has now enabled the ability to acquire up to 4096 repetitions with 3 echoes. Many thanks for the tip!
