### ISSUE TITLE
Planned support for NX VA10A?

### ISSUE THREAD

**Issue by lucijj** [CMRR-C2P/MB#211]
We just took delivery of our new Vida. It runs Numaris 10 (NX) VA10A. Do you plan to support that line of scanners? We much prefer to use your MB rather than move to the product SMS! But, we understand that the prospect of supporting yet another platform is . . . suboptimal.

**Comment by eauerbach** [comment]
That is a good question. I have only seen a Vida once at the factory and it is obvious how the UI has changed, but I have no idea what changes there may be to the development environment (is it even released yet?) and how much work it would be to port existing customer sequences. I am willing to work on it, as I suppose it is inevitable that everything will go in that direction eventually, but I can say nothing will happen until later in the summer based only on my own schedule (late July at the earliest). Getting access to all of the needed bits from Siemens (and time on a Vida somewhere if necessary for troubleshooting) could change that schedule... I will start looking into it and follow up at ISMRM.

**Comment by lucijj** [comment]
Yes, you can get the IDEA disk from Siemens as of about three weeks ago. Vibhas Dishpande told me he had it delivered to someone at CMRR already. I didn't ask who because I assumed it was you, but obviously, that's not correct.

We completely understand the timeframe for development, and know it will take a while. We greatly appreciate everything you're already doing!

If you want us to serve as a development or beta site for this, I'm happy to provide support, staff time, and magnet time for testing. Just let me know if there is anything we can do to help out. Good luck at ISMRM!

**Comment by lucijj** [comment]
I learned today that VX11A will probably be released soon. Siemens isn't even training FSE's with VX10A. This is consistent with how Siemens introduced the Skyra on the beta-like VD10, and bumped to VD11 almost immediately. Of course, I don't know if there will be pulse programmatic differences between VX10A and VX11A, but until we know, I'm not sure I would dedicate significant resources developing a VX port. That's me though. I don't have anything close to your user base for IDEA or ICE tools, and your parameters are a lot different. I just thought you might want to know that little tidbit of info if you didn't already.

**Comment by eauerbach** [comment]
Ok, as of last week I have received IDEA for 10A and 10A-SP1, which I assume are incompatible. I will ask about 11A. Usually the odd numbers are the official wide releases and the even numbers are limited releases for testing or for special systems so that makes sense. We'll see how the timing works out; if it is going to be more than a few months for 11A then perhaps I will send something out for testing on 10A-SP1 (I assume that is what you have now?).

**Comment by lucijj** [comment]
Yes.  Well . . . we have 11A right now.  SP1 will/should be installed next week.

**Comment by eauerbach** [comment]
I started looking at 10A-SP1...it is going to be a while.

**Comment by lucijj** [comment]
I understand. No worries. Shout if you need anything.

Jeff

**Comment by lucijj** [comment]
Hi again:

We just upgraded to NX-VA11B last week. I don't think there is much use in working towards VA10A. There shouldn't be very many of those left in the world, and all of them would be eligible for upgrade to at least VA11A.

**Comment by eauerbach** [comment]
Well, I never managed to get the VA11A tools despite many requests, so we'll have to see how it goes with VA11B...

**Comment by lucijj** [comment]
Hi again:

Just checking in to see if you have any impressions of the NX-VA11 development. We're getting more demand for your tools on that scanner now, and several other places with new Vidas have asked me for advice on using the product SMS which just isn't nearly as nice for research work - especially diffusion. I understand demand for this is low, but it would be helpful if you can say if you think this will actually happen. If not, I can start to make other arrangements.

As always, thanks for everything!

**Comment by eauerbach** [comment]
I can look into it again. What is the current version?

**Comment by lucijj** [comment]
We're on NX-VA11B. Unfortunately, I can't find a baseline string anywhere. Our Siemens research guy couldn't even locate it. So, maybe they've changed how they keep track of that? If I figure that out, I'll update you here.

**Comment by eauerbach** [comment]
I understand XA20A has been approved. Do you have an idea if/when your system will be upgraded? I'm wondering if it is worth it to bother with VA11B at this point.

**Comment by lucijj** [comment]
I hadn't heard that, but if that's true, then, yeah, I would abandon any A10 or A11 development as anyone with those systems in research setting is likely to have an eVolve agreement and eligible for an upgrade to A20. Since A10/11 is so buggy, we will be insisting on upgrading as soon as possible. I have already asked our Uptime rep to inquire about it.

Do you have the XA20A IDEA disk yet? If so, who issued it? Our research contact isn't answering e-mails right now (presumably due to the CV stuff).

**Comment by eauerbach** [comment]
I have been offered and have requested IDEA for XA20A but I do not have it yet. I assume it will be weeks/months before I have something working, maybe in the same timeframe it will be rolling out to systems...

**Comment by lucijj** [comment]
That's great news! If you need a test platform, just say the word. We have expert-i, so we might even be able to arrange for you to log in remotely (assuming we can get the VPN credentials for you approved).

**Comment by OlivierMGirard** [comment]
Hello,
I am jumping into this discussion as we will be having a Vida soon running under XA20A as well, and we would be happy to use your sequence on that system as well. We've been running the VB17 version for a long time, and it is great, and we would like to go one using the MB instead of the Siemens product.

**Comment by eauerbach** [comment]
I'm going to close this one, XA10/11 are obsolete at this point, R017 will target XA20 and XA30
