### ISSUE TITLE
Image recon error - Prisma VE11C

### ISSUE THREAD

**Issue by MC-Brighton** [CMRR-C2P/MB#213]
Hi there,

We are having a  recurring problem with the MB BOLD EPI sequence. We are using the HCP protocol with MB=8 and TR=800ms. We have a siemens Prisma, software version VE11C.

During the acquisition, the scanner stops with the error "Scanning stopped by image reconstruction". At this point the only way of re-starting the measurement is by rebooting the scanner.

Of note: this problem has only ever happened when using the 64-channel coil, but never with the 32-channel coil.
I would be very grateful for any suggestion.

Thank you and best wishes
Mara

**Comment by eauerbach** [comment]
This is known to happen sometimes when using the 64-channel coil; in general we don't recommend using the 64-channel coil (32-channel coil seems to always be preferred). If you want to use the 64-channel coil, you can avoid this error and speed up the recon by setting the "Matrix Optimization" option on the System/Miscellaneous card to "Performance".
