### ISSUE TITLE
ME echo times not saved in DICOM

### ISSUE THREAD

**Issue by KevinAquino** [CMRR-C2P/MB#214]
Hi all,

We are scanning ME & ME+MB sequences and it seems that the DICOMs are not saving the echo times -- looking at the DICOM headers this field is empty/non existent, are they encoded in a specific tag (that dcm2niix ignores)? we scanning on a Skyra using CMMR version R16a.

Thanks!

**Comment by eauerbach** [comment]
Each echo is stored in its own (Mosaic) DICOM image, and the echo time field is filled with the correct TE for each image. If you look at the images on the scanner you should be able to see the different TE values for each image. If that is being lost, then I would suspect your DICOM receiver or dcm2niix is dropping them.
