### ISSUE TITLE
Scanning regularly interrupted during MB-EPI acquisition (VB17A) 

### ISSUE THREAD

**Issue by FGrouiller** [CMRR-C2P/MB#215]
Hello, 

During the last few months, we regularly an error that stop the acquisition of MB-EPI in our scanner. "The error message is Image Reconstruction failed. Scanning stopped by Image Reconstruction". After this error, we can restart the sequence immediately without any problem. The problem seems to occur completely randomly and not very frequently (once every 1-3 weeks whereas we are using this sequence in most of our protocols). 

We are using sequence R016a for VB17A with a TRIO and we are using a remote reconstruction server.
Does anybody else have the same problem with the last realease and do you have any idea from where this problem come from? If it can help, we saved the scanner logfiles.
Thanks in advance for your feedback!

Frederic

**Comment by jpyles** [comment]
I'm not sure if it is the same issue, but we had continuous reconstruction problems even with a remote reconstruction server on our Verio running BV17A (see #160). Upgrading to a Step5 imager solved the problem. There was instability in the Step4 that nothing seemed to solve. Analysis of our log files pointed to disk write problems in the MRIR or potentially RAM, but nothing we could ever replicate reliably. If you have Siemens Evolve I'd highly recommend getting a Step5 if you can. They should offer it with the ability to stay on VB17A if you ask.
