### ISSUE TITLE
"gradient error insufficient voltage"

### ISSUE THREAD

**Issue by swrieger** [CMRR-C2P/MB#220]
Hi all,

we had an error running an MB protocol on a VE11C Prisma. Scanning stopped part way through a run, and the error message said something along the lines of “gradient coil error, insufficient voltage”. It was a 2mm resolution, MB3 PAT2 protocol with TR/TE=1235/20ms. We have used this lots of times before without problems. A Siemens engineer looked into it and said there was a glitch in the digital RF receiver. This is from their report:

"Degital receiver error suggests:
The incoming data rate of the measurement data is too high.
.) Increase TR or reduce resolution, NoOfSlices, NoOfAverages,
NoOfSelectedCoilElements.
2.) If the sequence is not a Siemens sequence modify sequence.
The time between the ADC sampling intervals is too short.
1.) Increase echo spacing or TE respectively.
2.) If the sequence is not a Siemens sequence modify sequence.

A reboot seems to have fixed it, but any insight would be appreciated, in case it happens again.

Best wishes,
Seb

**Comment by eauerbach** [comment]
It does seem like a "random" glitch...your protocol is not especially demanding.
