### ISSUE TITLE
Recon errors Prisma fit on VD13D MB 8

### ISSUE THREAD

**Issue by MRC-CBSU** [CMRR-C2P/MB#224]
Dear Community,

Recently we started to experience intermittent errors with reconstruction when running MB 8 sequence (taken from the Connectome protocol). This sequence outputs 50GB of images each series. I am assuming this is not ideal for the image recon.

We are keeping the database at more than 25% free just to be on the safe side but still it happens. What is more worrying is that there are no errors/warnings displayed and you only find out when the complete series or images of it are missing. Using the retro recon tool we can retrieve the raw data but most of the time the recon fails. 

Any comments/experience is greatly appreciated.

**Comment by eauerbach** [comment]
This is a known problem on VD13D. We were eventually able to replicate it using only Siemens product sequences--it can happen with any sequence under heavy load. As far as I know there is no solution but to upgrade the software to VE11C. Rebooting the system frequently may help a bit, but as far as I can recall it is no guarantee (we got to the point where we were rebooting daily and/or immediately before any demanding session, but the problem never completely went away until the software was upgraded).
