### ISSUE TITLE
VE11E version?

### ISSUE THREAD

**Issue by takuya-hayashi** [CMRR-C2P/MB#226]
Dear Community,

We are planning whether our system should be upgraded to VE11E. It would be great if you have plan to release MB-EPI for VE11E in the next release of June 2019?

Thanks,

**Comment by eauerbach** [comment]
I have not heard of VE11E. What type of system is it for and when is the expected release?

**Comment by takuya-hayashi** [comment]
Siemens told me that release of VE11E will be a bit delayed but perhaps
around July to Sep of this year.
The VE11E is for those scanners currently working on VE11C such as Prisma,
Skyra, Aera.

Takuya

2019年3月19日(火) 0:05 Eddie Auerbach <notifications@github.com>:

**Comment by eauerbach** [comment]
Yes, we will have a version for VE11E.

**Comment by o-dietrich** [comment]
Thanks! We're also going to upgrade our scanners to VE11E soon and depend on your MB-EPI.
Olaf

**Comment by dcbrien** [comment]
We will also be on VE11E starting this fall with our Prisma.  Any ETA on this?

**Comment by eauerbach** [comment]
Does anyone have VE11E already?

**Comment by eauerbach** [comment]
The VE11E version is now released.
