### ISSUE TITLE
Enable 2nd ethernet port

### ISSUE THREAD

**Issue by mckib2** [CMRR-C2P/MB#227]
We have a step 5 imager using VB17 Tim Trio.  We are trying to set up a direct connection between the imager and our offline reconstruction machine but have been unable enable the eth1 port on the imager.  We have already tried running the script on the Host to enable the port but were unsuccessful.  We have already asked both our service support and research rep how to enable it but have been unable to resolve the issue.  When we ssh into the imager eth1 is not listed as network device when we run ifconfig.  We suspect that it is disabled in BIOS but we are unable to access it.

Any ideas on how to enable the second port?

**Comment by eauerbach** [comment]
I have never seen a Step5 imager in the wild. Assuming you are looking at an open RJ45 port, it is possible that it is disabled in the BIOS, although Siemens has not historically done that. It is also possible that it is not actually ethernet, but a dedicated IPMI port. Did you check with `ifconfig -a`?

In any case, if you can get that port to work, it is almost certainly only 1 GbE. That will not be fast enough to stream 32-channel raw data in real time (if that is your intent).

**Comment by mckib2** [comment]
It is an RJ45 port and does not show up when we run `ifconfig -a`.  Currently we're using the Siemens private network with a switch to hook up our offline recon machine.  But we want to avoid the use of the switch because we are getting random intermittent errors during reconstruction that halts the currently running scans.  We are looking into getting a 10 GbE card, but we're hoping to use the secondary port in the mean-time.  There is a 3rd port that is used for IPMI, but seems to be disabled as well.

**Comment by eauerbach** [comment]
I can only imagine it is disabled in the BIOS then. You definitely should not use the existing private network because it is sure to produce the errors you are seeing. If you are comfortable modifying the system I would say 10GbE is the way to go, but it would also be an easy thing to try to enable the existing port in the BIOS (have you tried it?).
