### ISSUE TITLE
No trigger multi-echo R016a VE11C

### ISSUE THREAD

**Issue by pimpul** [CMRR-C2P/MB#228]
We would like to acquire task-based multi-echo fmri, but the scanner does not generate a trigger pulse using the multi-echo option. We have tried different trigger schemes, but with no result.
We're using a PrismaFit VE11C, R016a.

Best,

Pim Pullens
Gent University Hospital, Belgium

**Comment by eauerbach** [comment]
There is no difference in the handling of trigger signals in the pulse sequence when multi-echo is enabled. Set the Triggering scheme parameter on the Sequence/Special card to 'Standard' (the default) and you will get one trigger for each measurement. You will not get an additional trigger for each echo if that is what you are expecting.

**Comment by dcbrien** [comment]
Somewhat related to this, if the trigger is set to standard, there is one trigger per volume, but not for the reference scan, correct?

**Comment by eauerbach** [comment]
Correct, the first trigger marks the first fully reconstructed volume. Depending on the protocol there may be single-band reference scans, iPAT reference scans, and/or discarded steady-state preparation scans prior to the first trigger.
