### ISSUE TITLE
Add trigger for cmrr_mbep2d_diff

### ISSUE THREAD

**Issue by julfou81** [CMRR-C2P/MB#233]
Hi,

I was wondering if it would be possible to have the possibility to send triggers every TR (and every slice) with the sequence cmrr_mbep2D_diff, similar to what is available for the cmrr_ep2d_bold?
This would be useful for auditory systems providing active noise cancelling, based on the timing of the sequence.

Thank you!

**Comment by eauerbach** [comment]
Did you try it? I think it does this already...

**Comment by julfou81** [comment]
Sorry for the slow feedback! Yes it is there indeed! We will check how the active noise cancelling works for that sequence!
