### ISSUE TITLE
Diffusion Free Mode not available

### ISSUE THREAD

**Issue by dcbrien** [CMRR-C2P/MB#237]
I'm not sure if this is a bug or not, but when I start with the base diffusion sequence I do not see free mode as an option.  However, if I import a diffusion scan that had free mode selected already from a previous version, it appears.  VE11E Prisma Fit.

**Comment by eauerbach** [comment]
You may need to create the folder DiffusionVectorSets under C:\MedCom\MriCustomer\seq. If this folder does not exist, the Free option will not appear in a new protocol. The folder can be empty, but it must exist.

**Comment by dcbrien** [comment]
Thank you.  This solved it.
