### ISSUE TITLE
unit of phase images?

### ISSUE THREAD

**Issue by lcnature** [CMRR-C2P/MB#238]
Hello,
I am attempting to make use of the phase information of the multi-band EPI data. I found the numbers of the phase images are quite big (a few thousands). When scanning a phantom, once the phase exceeds some number a bit more than 4000, its adjacent voxels would be flipped to a negative number a bit larger than -4000. So I assume that this wrap around roughly corresponds to the wrapping around of 2*pi. But I don't know the exact correspondence - how to convert these numbers to radius?

**Comment by lcnature** [comment]
Oh, I now think that the range is from -4096 to 4094. Shall I infer that if I multiply the image value by pi/4096, I should get a number in raidus?

**Comment by eauerbach** [comment]
Phases are always specified in the range of -pi,+pi and are either scaled to -4096=-pi,+4095=+pi or 0=-pi,+4095=+pi (where +2048=0). I don't remember if this changes by the software version, but it may be that phase images are the former and phase difference images are the latter.

**Comment by lcnature** [comment]
Thanks so much for the explanation! It makes sense to me now. I just noticed that the stored phase values are all even numbers. So the highest goes to 4094.
