### ISSUE TITLE
Ground ECG electrode

### ISSUE THREAD

**Issue by jrasero** [CMRR-C2P/MB#243]
Hi,

We have collected physiological data using CMRR multiband version R016a on a Prisma running VE11C and extracted them into log files using the Matlab script **extractCMRRPhysio.m** in this repository.

For the ECG signal, there are 4 electrodes (ECG1, ECG2, ECG3 and ECG4) and we suspect that one of those might be a ground electrode. We tried to find this information in the Siemens manual as well as googling it, but we found nothing.

Any clue on this?

Thanks a lot in advance!!

**Comment by eauerbach** [comment]
I don't use these signals personally, but my understanding is that the four ECG signals are from the three leads and the calculated VCG. I don't know the order.

**Comment by jrasero** [comment]
> I don't use these signals personally, but my understanding is that the four ECG signals are from the three leads and the calculated VCG. I don't know the order.

Hey @eauerbach , sorry for taking so long, but I accidentally skipped your reply. Thanks a lot! So according to your reply, the four ECG signals can be individually used as a signal to preprocessed and analysed? No need to subtract one to another?

Thanks!
