### ISSUE TITLE
units for physiological data 

### ISSUE THREAD

**Issue by kmbond** [CMRR-C2P/MB#244]
Hi, 

This is a rather basic question, but one that doesn't appear to have a ready answer. Do you know the units for: 

1) respiration data
2) pulse data
3) EKG data (microvolts?)

Thanks! I appreciate any leads you can give.

**Comment by eauerbach** [comment]
I don't know about the EKG data, but the pulse and respiration are automatically scaled so you can't assume they are anything but arbitrary.
