### ISSUE TITLE
Multiband shift factor

### ISSUE THREAD

**Issue by randomprogram** [CMRR-C2P/MB#246]
Dear all,

Does anybody know how to find out the multiband shift factor from either the DICOM header or the twix raw data?

Thanks,
Deqiang

**Comment by eauerbach** [comment]
The MB acceleration factor or the PE FoV shift factor (for blipped-CAIPI)?

In the DICOM, the easiest is to look in the image comment as both are specified there (e.g. "Unaliased MB8/PE3" for MB acceleration of 8, PE FoV shift 1/3).

In the raw data, within the XProtocol there are a couple places you can find "alICEProgramPara". The acceleration factor is alICEProgramPara[11]; the PE FoV shift is alICEProgramPara[14] (starting from [0]).

**Comment by randomprogram** [comment]
This helps a lot, thanks!

**Comment by mharms** [comment]
Does anyone know if the CAIPI shift factor is embedded in the Siemens DICOMs anywhere else (than the "Image Comments" field for the CMRR sequences)?  e.g., for the Siemens product SMS sequences?
