### ISSUE TITLE
Multiband EPI for VE11P SP4

### ISSUE THREAD

**Issue by matthiasruf** [CMRR-C2P/MB#247]
Hi,
would it be possible, that you supply a VE11P SP4 version of your Multiband EPI sequence for the Biograph mMR? We had to install this service pack recently.
Thanks a lot,
Matthias Ruf

**Comment by eauerbach** [comment]
Yes, it is available on the web site now.

**Comment by matthiasruf** [comment]
Hello Eddie,

Thanks a lot. This saves our study.

Best regards

Matthias Ruf

[cid:image001.png@01D4FDAE.016B40D0]

Matthias Ruf
Deputy Head | Dipl.-Ing.
Department of Neuroimaging
Core Facility ZIPP
Central Institute of Mental Health
J 5 · 68159 Mannheim
Phone: + 49 621 1703-2976<tel:+%2049%20621%201703-2976>
matthias.ruf@zi-mannheim.de<mailto:matthias.ruf@zi-mannheim.de>
www.zi-mannheim.de<http://www.zi-mannheim.de/>

Executive Board: Prof. Dr. Andreas Meyer-Lindenberg, Dr. Matthias Janta
President of the Supervisory Board: Dr. Carsten Dose

Am 05.08.2020 um 21:58 schrieb Eddie Auerbach <notifications@github.com>:

﻿

Yes, it is available on the web site now.
