### ISSUE TITLE
VB17 ep2d_diff with only 3 diffusion directions ?  

### ISSUE THREAD

**Issue by benediktposer** [CMRR-C2P/MB#252]
someone here wants to use the diffusion mb sequence for IVIM, with very few diffusion directions (only 3) 
is there a way to do this, given that only MDDW and FREE mode are available?  

( I believe MDDW is only >= 6 directions, and same Siemens GUI limit might apply to the FREE mode? )

Thanks!

**Comment by eauerbach** [comment]
Did you try it and see an error? I think it may work in Free mode, but you can not use any of the post processing options. I think it may also disable mosaic automatically. It has been a while since I looked at this, I don't think there is any problem on the sequence side but there are potential ICE issues.

**Comment by benediktposer** [comment]
Thanks! 
I did try put a section with only 3 directions at the top of  the DiffusionVectors.txt  but in FREE mode the min number of directions that showed up in the GUI was still 6... 
I did not check however if there was a (silent) error being logged in the GUI backend

**Comment by whitecraine** [comment]
Throwing some ideas out here since it looks like we may be short on options! Would it help if you repeated the same 3 dir twice in the 6 dir table (free average!)? Alternatively, could you have the scan operator just stop the scan after the 3rd direction finishes acquiring? Alternatively, you could try setting up a protocol such that the 4th direction automatically causes the scanner to abort.

**Comment by xjqian** [comment]
Given any diffusion protocol is likely going to need many averages, I would concur with Joseph's suggestion to pad the table to multiple repeats of the 3 directions. On top of that, you can reverse the gradient polarity for every other repeat to achieve a cross-term free table.

**Comment by benediktposer** [comment]
thanks @whitecraine and @xjqian for your suggestions and comments!
using the 6dir table and manual stopping after the first 3 (or, indeed if that works, setting the 4th to cause  as sequence abort) would seem the  "best" way forward. 
Since this is for a clinical IVIM protocol with manymany b-values there is no time for averaging, reversal ect . TR is very long due to high SAR at 7T from the inversion  ( also, all single-band) and the time it takes for 3 directions is already pushing hard on the limit of what we can afford (even with relatively coarse resolution and only ~40 slices.)
if anyone else at there has IVIM experience with this sequence, I'd be curious to hear! :-)

thanks guys!

**Comment by whitecraine** [comment]
Oh! Sorry missed the part where you were acquiring many b-values (i.e. runs). It sounds then that you actually want a longer table (maybe something like 3 x # of b-values). You could then set the b-value of the scan to the max desired b-value and then scale the individual table entry vectors appropriately to achieve the desired smaller b-values. This is how the HCP achieved 50, 1000, 2000, and 3000 b-vals in one table/acquisition. Let me know if this makes sense or maybe I'm still misunderstanding.

**Comment by benediktposer** [comment]
thanks Joseph, that seems to be the best way forward yet  (maybe something like 3 x # of b-values).
Always in fear of messing up existing DiffusionVectors.txt files, and being pretty naïve to setting up diffusion protocols  ( if this hasn't been really obvious by now ;-)  ): is there a way to read diffvec files with a custom filename that get's only used for a particular protocol? I I think I heard that's possible, by putting a proper string into the the protocol name if I remember correctly.. ?

**Comment by whitecraine** [comment]
That's great to hear Ben! This will also save lots of overhead time (fewer reference scans). Regarding use of custom diffvec files, hopefully Eddie or Gordon can chime in. I've not had to do this on VB17. As long as the number of directions is unique in the table (and you backup the working .txt file), you should be fine.

**Comment by benediktposer** [comment]
thanks again @whitecraine, this suggestion/solution below worked just perfectly! 

> Oh! Sorry missed the part where you were acquiring many b-values (i.e. runs). It sounds then that you actually want a longer table (maybe something like 3 x # of b-values). You could then set the b-value of the scan to the max desired b-value and then scale the individual table entry vectors appropriately to achieve the desired smaller b-values. This is how the HCP achieved 50, 1000, 2000, and 3000 b-vals in one table/acquisition. Let me know if this makes sense or maybe I'm still misunderstanding.
