### ISSUE TITLE
Problems with timing of PhysioData

### ISSUE THREAD

**Issue by TinaUOL** [CMRR-C2P/MB#253]
Dear all,

we are trying to use the physio data (only pulse) recorded with the CMRR MB sequence in a Magnetom Prisma (VE11C). We used the extractCMRRPhysio.mat provided here. 

However, we discovered some questions/problems.
1) In some measurements, there is an _ECG.log and a _RESP_log with data points in it, even if we only put the pulse oxy on. How could that happen?
2) What is the exact sampling rate of the pulse data? Here (https://gitlab.ethz.ch/physio/physio-doc/-/wikis/MANUAL_PART_READIN) I found that for pulse data it may be only 20ms, however, when I check the ACQ_TIME_TICS in the logfile it is obviously 2.5 ms. Is this correct? The sampling rate for all ECG, Pulse and RESP is 400 Hz when recorded within the MB sequence?
3) To synchronize the Pulse data with the BOLD data, I used the ACQ_START_TICS in volumne 0 slice 0 as logged in the info.log and tried to find the same timepoint in the pulse.log. The same for the end of the measurement with the ACQ_FINISH_TICS. However sometimes the timestamps in the log file did not correspond to those in the pulse log file. How could this happen. In some cases there are even in others odd numbers. Is there a good solution to solve this problem? 

Attached is an example with data in the ECG and RESP even we did not record this and the problem that the acq_finish_tics can not be found in the pulse data.

Any comments would be helpful. Many thanks in advance,

Tina

[Physio_20200921_115743_34bd1d96-98cf-4da9-a0d7-694940a2555b_RESP.log](https://github.com/CMRR-C2P/MB/files/5428470/Physio_20200921_115743_34bd1d96-98cf-4da9-a0d7-694940a2555b_RESP.log)
[Physio_20200921_115743_34bd1d96-98cf-4da9-a0d7-694940a2555b_ECG.log](https://github.com/CMRR-C2P/MB/files/5428471/Physio_20200921_115743_34bd1d96-98cf-4da9-a0d7-694940a2555b_ECG.log)

[Physio_20200921_115743_34bd1d96-98cf-4da9-a0d7-694940a2555b_PULS.log](https://github.com/CMRR-C2P/MB/files/5428468/Physio_20200921_115743_34bd1d96-98cf-4da9-a0d7-694940a2555b_PULS.log)

[Physio_20200921_115743_34bd1d96-98cf-4da9-a0d7-694940a2555b_Info.log](https://github.com/CMRR-C2P/MB/files/5428467/Physio_20200921_115743_34bd1d96-98cf-4da9-a0d7-694940a2555b_Info.log)

**Comment by TinaUOL** [comment]
Dear all, 
unfortunately I did not receive an answer so far. Could somebody help me with this issue, please?

Best regards,
Tina

**Comment by alexsayal** [comment]
Hello @TinaUOL,

I can provide some user input on question 2. All signals are acquired at 2.5 ms (400 Hz) but recorded in the text file at different sampling rates - the file skips certain 'tics' (i.e. time units of 2.5 ms), and only writes out every 'SampleTime' sample into the logfile, as indicated in its header: the PULS signal at 5 ms (200 Hz, SampleTime=2) and the RESP at 20 ms (50 Hz, SampleTime = 8).

Hope somebody else can help with the other questions!

Best,
