### ISSUE TITLE
Request: inverse of extractCMRRPhysio.m

### ISSUE THREAD

**Issue by alexsayal** [CMRR-C2P/MB#254]
Hello all,

I want to use a script that reads the DICOM physio file to create .tsv files compatible with the BIDS standard. However, my files are in .log format.

Would it be possible to create a script to convert from individual log files (*_ECG.log, *_RESP.log, *_PULS.log, *_Info.log) to the "_PHYSIO" DICOM file (i.e., the inverse of extractCMRRPhysio.m)?

I really appreciate any help you can provide.

**Comment by eauerbach** [comment]
It looks like this is in the BIDScoin toolbox https://github.com/Donders-Institute/bidscoin 
e.g. physio2tsv.py can read either the .log files or the DICOM

**Comment by pvelasco** [comment]
You can also try [bidsphysio](https://github.com/cbinyu/bidsphysio)
