### ISSUE TITLE
VE11D Version?

### ISSUE THREAD

**Issue by BlancheBapst** [CMRR-C2P/MB#255]
Dear Community,

Our Verio system has been upgraded to VE11D. It would be great if you have plan to release MB-EPI for VE11D ?

Thanks a lot,

Blanche

**Comment by eauerbach** [comment]
I can check on that

**Comment by eauerbach** [comment]
According to Siemens there is no support for WiPs and customer sequences for VE11D, so unless something changes on their end I don't expect versions of the C2Ps to be available.
