### ISSUE TITLE
XA support

### ISSUE THREAD

**Issue by mimarxen** [CMRR-C2P/MB#258]
Soon the Siemens Prisma / PrismaFit will be shipped with the XA software (XA30?), which is already the default for the Vida system.
Are you working on a compilation of the MB-software for XA? If so, any idea when it will be available?

Best regards,
Michael  Marxen
TU Dresden

**Comment by eauerbach** [comment]
XA20 and XA30 are targeted for the R017 release (soon?)

**Comment by mharms** [comment]
Any update on the timing for XA20 and XA30 support?  Thx.

**Comment by eauerbach** [comment]
Still waiting on code from Siemens...

**Comment by muratakatsutoshiuiop** [comment]
Dear Dr. Auerbach,
I am K. Murata (Mr.) working in Siemens Healthcare, Japan.
My collaboration partner will get Prisma fit with XA version, soon.
He used your MB-EPI on Trio A Tim System and wishes to continue using MB-EPI even after Prisma fit UG.
Did you already get source codes of XA version from Siemens?
Will R017 be released in January 2022?
Your kind information is highly appreciated.
Best Regards,
K. Murata

**Comment by mimarxen** [comment]
Dear Eddie, we currently have to decide between VE and XA30 for your PrismaFit upgrade in February, 2022. Is there any news on R017 for XA30?

Best, Michael

**Comment by eauerbach** [comment]
If anyone has a system currently running XA30 and would like to test the sequences now, please contact me. I am looking for a few more test sites.

Also I am debating whether to release sequences for XA20. My understanding is that all XA20 sites are expected to update to XA31, so I am considering to skip XA20. If anyone has particular feelings about this, let me know.

**Comment by TimmWetzel** [comment]
Dear Eddie,

> On 14. Dec 2021, at 16:03, Eddie Auerbach ***@***.***> wrote:

> If anyone has a system currently running XA30 and would like to test the sequences now, please contact me. I am looking for a few more test sites.

great news! 
I would very much like to run tests — we are running a Prisma_fit freshly upgraded to XA30.


Best Regards,
Timm

**Comment by tetsumatsuda** [comment]
> If anyone has a system currently running XA30 and would like to test the sequences now, please contact me. I am looking for a few more test sites.
> 
> Also I am debating whether to release sequences for XA20. My understanding is that all XA20 sites are expected to update to XA31, so I am considering to skip XA20. If anyone has particular feelings about this, let me know.


Now we updated a system from Siemens Trio-Tim to Prisma fit running XA30.  
I'm very interested in testing the sequences.

Thanks,
Tetsuya

**Comment by jamyandy** [comment]
Dear all,
How is the XA30 testing going?
We also updated Siemens Trio-Tim to Prisma fit XA30.
I also am available to test the sequences,
best
J.A

**Comment by mimarxen** [comment]
Dear Eddie,
Our PrismaFit scanner is now operational with XA30. We are really under pressure to update our CMRR protocols. A short-term solution may be to install the beta testing version.
Would that be a possibility? Are there serious concerns that the beta version of R016a has image quality issues as compared to the VE/VB version? The R017 version would not be essential for us.
We would be very happy to assist with testing the XA versions.

Best, Michael

------------------------------------------------------------------------------------
Michael Marxen, Ph.D., Dipl.-Phys.
Group Leader Brain Dynamics and Imaging Methods
Department of Psychiatry and Neuroimaging Center
Technische Universität Dresden
Würzburger Str. 35
01187 Dresden
Germany

Phone:  +49 (351) 46342212
Fax:      +49 (351) 46342202
E-Mail:  ***@***.******@***.***>
Web:    https://nic-tud.de/research/grps_med/brain-dynamics-group
------------------------------------------------------------------------------------

**Comment by wang-zhan** [comment]
Dear Eddie,

Does the XA30 version still support the multi-echo features? 

We have a coming new project that  is set use the multi-echo multiband scans. Please confirm. Many thanks!

Wang

University of Maryland, College Park

**Comment by eauerbach** [comment]
Yes, all of the current features including multi-echo are still supported; in addition there are several new features (3D being the most significant).

**Comment by natalia-zaretskaya** [comment]
> If anyone has a system currently running XA30 and would like to test the sequences now, please contact me. I am looking for a few more test sites.
> 
> Also I am debating whether to release sequences for XA20. My understanding is that all XA20 sites are expected to update to XA31, so I am considering to skip XA20. If anyone has particular feelings about this, let me know.

Dear Eddie,

we are running MAGNETOM Vida just updated to XA31 - we would be happy to help with testing if you still need us.
Just let me know!

Natalia

**Comment by BBellenberg** [comment]
Dear Eddie, we are also running a VIDA sytem with XA31 and would like to use the MB software. We would be happy to test the sequences on XA31. If there is need for that, please contact me.

Barbara

**Comment by eauerbach** [comment]
Moved to #288
