### ISSUE TITLE
HCP multiband sequence license

### ISSUE THREAD

**Issue by bbfrederick** [CMRR-C2P/MB#262]
Hi,

I updated our MB-EPI license last week to the version that expires on 29 Jan 2022, and that seems to make the CMRR MB sequences happy, but today, a protocol that uses of the hcp_cmrr sequences failed saying the license expired on 31 January 2021.  Is this a different license file?  Is there a renewed version of it?

Thanks,
Blaise

**Comment by pvelasco** [comment]
When you copied the new license file to the destination folder, were you in the “Update Mode”?
Otherwise the system will not recognize the new file.

**Comment by eauerbach** [comment]
Those HCP sequences are not distributed publicly, you should have received some information about how to update those from HCP contacts (e.g. Essa). There is no license update for those very old sequences, they have to be replaced.
