### ISSUE TITLE
Phase scrambling active at MB2 despite what documentation and tooltip say

### ISSUE THREAD

**Issue by julfou81** [CMRR-C2P/MB#267]
Hi,
I observed an effect of the phase scrambling option when I was doing some testing on a phantom with MB=2 even the though in the documentation it is mentioned that this option is activated for MB=3-8.
I show you the comparison: 
**-top left:** no option activated (only SENSE)
**-top right:** phase scrambling activated
**-bottom left:** Leak Block Kernel activated
**-bottom right:** Double Kernel activated

Here is the temporal mean over 20 volume (no difference strickingly visible)
![MB2_TMEAN_nothing_phasescr_LB_D](https://user-images.githubusercontent.com/32452352/112134406-039b5480-8bcd-11eb-9f8d-39eae08477c9.PNG)

Here is the Temporal standard deviation over the same 20 volumes (the ghost is more pronunced for phase scrambling and LeakBlock)

![MB2_TSD_nothing_phasescr_LB_D](https://user-images.githubusercontent.com/32452352/112134546-27f73100-8bcd-11eb-850a-3a8eb3d3053f.PNG)

Here is the TSNR over the same 20 volumes (summary of the two observations above)
![MB2_TSNR_nothing_phasescr_LB_D](https://user-images.githubusercontent.com/32452352/112134613-37767a00-8bcd-11eb-90a6-1bf7f2604eeb.PNG)

Of course the agar phantom is not the best object to assess the MB sequence performances, but I was thinking that it is worth mentioning that the phase scrambling option does indeed something on the images with a MB=2 despite what the documentation and the tooltip say.

**Comment by eauerbach** [comment]
Yes, there is a phase scramble parameter for MB2 which really isn't meant to be used. I will remove it and fix the UI for the next version.

**Comment by julfou81** [comment]
Great! Thank you Eddie!
