### ISSUE TITLE
Are requests for remote recon servers are still being accepted?

### ISSUE THREAD

**Issue by whitecraine** [CMRR-C2P/MB#270]
Can someone advise if requests for remote recon servers are still being accepted? One site I am collaborating with is still on VB17 Trio and is wondering if this might be an option available to them to speed things up.

_Originally posted by @whitecraine in https://github.com/CMRR-C2P/MB/issues/268#issuecomment-843670784_

**Comment by eauerbach** [comment]
Yes, for VB17A systems with the Step4 imager it is still an option.

**Comment by whitecraine** [comment]
Thank you Eddie! Siemens says that one has a Step5. Hopefully they can get it to work. I think I saw some other threads that mentioned getting it to work with Step5.
