### ISSUE TITLE
Physio files not saved

### ISSUE THREAD

**Issue by Rosenberg78** [CMRR-C2P/MB#276]
Dear experts,

We have on occasion seen that the physio files are Not created in the C:/medcom/log/physio folder even though it is set to "File" for the Physio recording in the sequence/Special card. It only happens occasionally. Anyone know why this might happen and Is the DICOM perhaps a safer more reliable option here?

Thanks for your help
Jens

**Comment by alexsayal** [comment]
Hello @Rosenberg78,

Not sure why the files are not exported, but we had the same issue in our setup. The DICOM export format revealed to be more reliable and practical than the File option.

Then you can use the script provided in this repo to convert from DICOM to .log.

Best,
