### ISSUE TITLE
Plan to port some features of this C2P sequence into a product sequence

### ISSUE THREAD

**Issue by jcohenadad** [CMRR-C2P/MB#279]
Hi,

Thank you for developing, maintaining and disseminating this excellent MB-EPI sequence. 

At our center in Montreal we use it as the 'default' sequence for fMRI and DWI studies. Some users are concerned that the sequence is not a product sequence (problematic for multi-center studies, concerns for longitudinal studies, etc.).

Are the developers aware if Siemens is planning to incorporate some of the features of this C2P sequence?  Notably, the automatic inclusion of the AP/PA phase-encoding scans for distortions correction is a great feature.

**Comment by eauerbach** [comment]
I really don't know anything about that; Siemens did already select a limited subset of the design and features of the C2P to incorporate into the SMS product, but I am not aware of any future plans. I can say that we do put a lot of effort into supporting multi-center and longitudinal studies, e.g. by distributing and maintaining sequences for older software versions, in contrast to the product where typically only the newest software versions are supported.
