### ISSUE TITLE
CMRR MB Compatibility with Siemens Update MR015/21/R VE11E-SH02

### ISSUE THREAD

**Issue by TerynWilkes** [CMRR-C2P/MB#281]
Hello,

We were just notified by our local Siemens engineer that they have a required software update due by 3/11, the only details they could provide are below. Previous updates like this have caused issues with certain protocols, including past installs of CMRR MB. I’m checking to confirm if this update is compatible with the current version of MB for our VE11E scanner?

_Numaris/4 VE11E-SH02 is a service help based on Numaris/4 VE11E-SP02 and it includes
improvements of diffusion weighted MR imaging._

Thank you for your time and attention to this request.
Teryn Wilkes

**Comment by eauerbach** [comment]
I am not 100% sure, but I think this was released last year and I haven't heard of any issues with it.

**Comment by TerynWilkes** [comment]
OK, thanks Dr. Auerbach. We are waiting to hear back from the national ABCD study team as well, related to their version of the SMS sequence. When we do the update I'll report back here if any issues.

**Comment by jlisinski** [comment]
Hello, we have VE11E-SH02-F3 and R16a for VE11E won't run. Do you have a version compiled for VE11E-SH02-F3 by any chance? Thank you!

**Comment by eauerbach** [comment]
Please make sure you have the latest version of the VE11E sequence .zip file from the web site—when you attempt to install this using the installation utility, do you see an error that the baseline is incorrect?

**Comment by jlisinski** [comment]
We've installed the latest version and did not get an error when installing. It just doesn't show up.

**Comment by jlisinski** [comment]
The IDEA license was missing on our VE11E-SH02-F3 system. We were able to see the sequence once the IDEA license was installed by the service engineer. Thank you for all of your help!
