### ISSUE TITLE
Distortion correction grayed out

### ISSUE THREAD

**Issue by jcohenadad** [CMRR-C2P/MB#283]
Hi,

We are using the GRE MB sequence Release R016a for VE11C. Is it normal that the gradient non-linearity distortion correction is grayed out?

![IMG_5078](https://user-images.githubusercontent.com/2482071/158626854-ddfa6711-f11d-4194-a1b5-08c5885ee324.jpg)

P.S. Thank you for sharing and maintaining these awesome sequences!

**Comment by xjqian** [comment]
Yes, it has been intentionally disabled from early on.

**Comment by eauerbach** [comment]
That is actually disabled by Siemens in the product. It is incompatible with Mosaic images.

**Comment by jcohenadad** [comment]
noted, thank you for the quick answer
