### ISSUE TITLE
scans with MB>1 doesn't start anymore since 2 days ... ?

### ISSUE THREAD

**Issue by FranckLamberton** [CMRR-C2P/MB#286]
Hi everyone
Since yesterday, when a MB factor is greater than 1, the sequence stops during its preparation. The phenomenon is very strange and occurred without modifications on the scanner (PRISMA, VE11C) nor the protocols between Tuesday and Wednesday.

We performed many tests and the only useful remark for the moment is : "the sequence doesn't start if and only if the MB factor is greater than 1". The SMS sequence from Siemens works fine, as well as the other sequences, so from Siemens point of view, the scanner is in good health.

So, I tried the sequence with MB set at 1 and then set at 2 in order to copy the log.

When MB=2, I've find an error on lines 1531-1533 about CUDA Intializing :
33 | 2022-04-14 09:23:25.450366 | MrIrisContainer | ejaMBSliceUnwrapper: Instance 0 using GPU device 0 (thread 0) for calculation | 
33 | 2022-04-14 09:23:25.450376 | MrIrisContainer | ejaMBSliceUnwrapper: Initializing CUDA: driver version 5050, runtime version 5050 | 
33 | 2022-04-14 09:23:25.450482 | MrIrisContainer | ejaMBSliceUnwrapper: Instance 0 failed during cublasCreate(): 1 status = 0xc0000001 | 

Have you any idea about what happens ? Does one of the K10 could be "tired" ? 

Thank you in advance for your help.
Sincerely
Franck
[test_CMRR_EPI_MB2_KO.txt](https://github.com/CMRR-C2P/MB/files/8491015/test_CMRR_EPI_MB2_KO.txt)
[test_CMRR_EPI_MB1_OK.txt](https://github.com/CMRR-C2P/MB/files/8491016/test_CMRR_EPI_MB1_OK.txt)

**Comment by eauerbach** [comment]
Could be. I think on VE11C Siemens only uses one GPU, and also maybe they do not throw an error if a GPU is present but not functioning. If you delete the file `C:\Medcom\MCIR\Med\config\eja_hardware.ini` you can temporarily force the MB ICE to not attempt to use the GPU (the file will be recreated after a reboot). If that works you probably need the MaRS replaced.

**Comment by benoitberanger** [comment]
On VE11C, the MARS have double dye GPU. Using `nvidia-smi` when you are logged with ssh, you cans see 2 lines, one for each dye. 
@eauerbach could `nvidia-smi` show any sign in case of malfunction ?

**Comment by FranckLamberton** [comment]
Thank you very much for the quick answers !

I deleted the file and the sequence ran correctly ! Siemens has just told me that the MaRS will be replaced soon, hope the issue will be completely resolved.

```nvidia-smi``` confirmed the presence of the two K10 since the first issue with the sequence. Testing the two GPUs could be indeed very useful.

![Capture_nvidia_smi](https://user-images.githubusercontent.com/103670175/163556721-de743bb2-a4b8-46df-9e78-361785428125.PNG)
.

**Comment by FranckLamberton** [comment]
Hi everybody
The new MaRS resolved the issue. 
Thanks
