### ISSUE TITLE
XA30 version?

### ISSUE THREAD

**Issue by schwartd** [CMRR-C2P/MB#289]
Hello, 
We plan on an XA30 upgrade for our Prisma Fit this summer. Are there plans to port the CMRR multiband packages to XA30? 

Thank you very much for all your work!
Daniel Schwartz
Advanced Imaging Research Center
Layton Aging and Alzheimer's Disease Center
OHSU

**Comment by eauerbach** [comment]
Yes, the prerelease version is now available
#288
