### ISSUE TITLE
b-value was not  properly applied in ”Free” mode of R017pre

### ISSUE THREAD

**Issue by muratakatsutoshiuiop** [CMRR-C2P/MB#291]
Dear Dr. Auerbach,

Thank you very much for your great efforts for releasing R017pre.
My collaboration partner is really pleased with this release.

I installed it into Prisma fit at my collaboration partner site.
I found one issue in cmrr_mbep2d_diff.

My collaboration partner has used attached DVS file for his DTI protocol in the past.
The vector norms of DVS are corresponding to 0, sqrt(0.35) and 1.0.
So, he could get DWI images with b=0, 700 and 2000 by setting b=2000 on "Diffusion" tab.

With this DVS file and setting b=2000 on "Diffusion" tab, R017pre sequence output b = 0, 500, and 1450.
(In this DVS, "Normalisation = none" was declared.)

He tried the DVS file with Siemens product sequence (ep2d_diff) and found it work correctly.
He also found that the b-value which he got from cmrr_mbep2d_diff was actually applied b-value
by comparing signal decay of water phantom with the one from ep2d_diff.

This only happens in "monopolar" and not in "bipolar". 

Could you please check the behavior when "Free" mode is selected with "monopolar" ?

Your cooperation is highly appreciated.
[DiffusionVectors_53dir.zip](https://github.com/CMRR-C2P/MB/files/8973984/DiffusionVectors_53dir.zip)

Best Regards,
K. Murata

**Comment by eauerbach** [comment]
The new release R017pre5 can be downloaded from the web site now, this issue is fixed

**Comment by muratakatsutoshiuiop** [comment]
Dear Dr. Auerbach,
Thank you very much super quick response!
I really appreciate your support from the bottom of my heart.
Best Regards,
K. Murata
