### ISSUE TITLE
Error when calculating parameters for lower gradient stimulation

### ISSUE THREAD

**Issue by marcomeixner** [CMRR-C2P/MB#293]
Hallo,

instead of a suggestion I get an error in the following scenario: 
The gradient stimulation of the participant is in the red and I ask the software to suggest either lower gradient rise times or a larger slice thickness.

Thanks a lot for your efforts!

Best,
Marco
(from the NIC in Dresden, Germany; we use the XA30A version on a Prisma fit)

**Comment by eauerbach** [comment]
this is fixed in pre7 (and duplicate of #331)
