### ISSUE TITLE
No Physio logs using R017A on XA30

### ISSUE THREAD

**Issue by mimarxen** [CMRR-C2P/MB#296]
Hi,
Today we tried the Legacy mode to save Physio data from the scanner and found no data in ...\logs\Physio\.
Other modes are not available. 

Is there already a solution for this issue that avoids using the ideacmdtool?
I think, we may still be using the pre4 release.

Best, Michael

**Comment by eauerbach** [comment]
Did you manually create the Physio subdirectory? I think that is still necessary, the directory will not be created automatically. Of course the Legacy mode has issues so it isn't a great solution, e.g. I believe it cuts off after 5 minutes.

The proper solution seems to be to upgrade the scanner to XA30A-SP02, which as far as I have heard (in the short time it has been available) surprisingly appears to fix the issues causing the system to crash when using the DICOM physiology option. If so, we will recommend everyone upgrade to SP02 and the next release will re-enable the DICOM physiology option (and the 16-bit DICOM option).

**Comment by mimarxen** [comment]
The Physio directory existed but was empty. I believe it was created previously during a different test of the sequence, whether automatically or manually, I do not know. Just as a background info: the 5 minute limit also is an issue for the ideacmdtool when all signals are recorded but not when the recording is started separately for each signal, which is what we are currently doing.

SP02 will likely be installed on our system at the end of September. I am looking forward to the next release, then.
Best, Michael
