### ISSUE TITLE
R016a License Extension?

### ISSUE THREAD

**Issue by jpyles** [CMRR-C2P/MB#300]
@eauerbach I wanted to check back in about if R016a will be extended beyond 30 January, 2023 for those of us sticking with VE11C? It would be great if you could let us know what the plans are. If we're going to have to upgrade to R017 we need to start planning for testing.

Thanks so much for all your work as always!

--John

**Comment by chrysapa** [comment]
I wanted to echo John and ask whether R016 will be extended beyond January 30. Otherwise, we will have to install R017 (which also expires on January 30, but I am assuming that there will be a new license for it soon?).

Thank you!
Chrysa

**Comment by eauerbach** [comment]
Yes, both versions will be available for the foreseeable future (at least until R017 is officially released, which could be a while longer pending resolution of a few more XA issues). An updated license file that will update both versions is available on the web site now.
