### ISSUE TITLE
DWI with magnitude + phase export do not contain ImageType M/P

### ISSUE THREAD

**Issue by bpinsard** [CMRR-C2P/MB#305]
When exporting DWI with magnitude + phase data, the MB series do not contain M/P Magnitude/Phase while the corresponding SBRefs do. It results that the dicoms are not really identifiable in a simple robust automated manner for BIDS conversion (except comparing SeriesNumber).
Would that be realistic to fix?
I am not sure if that is CMRR-MB specific or inherit from Siemens code. 
Thanks

**Comment by eauerbach** [comment]
This is fixed in the next release

**Comment by bpinsard** [comment]
Fantastic! Thanks!
