### ISSUE TITLE
Request - support for XA50 - multiband EPI

### ISSUE THREAD

**Issue by robflintham** [CMRR-C2P/MB#307]
Hi.

Does the roadmap for multiband EPI include support for XA50+ software versions? We're a current user of this sequence on a Skyra on VE11E, but the centre are looking to upgrade the system to a Vida-Fit which will likely come with XA50.

Thanks!
Rob

**Comment by eauerbach** [comment]
Yes, I am working on this, it should be available shortly

**Comment by jhirschAtMEVIS** [comment]
Hi - great to hear that there is interest and activity.
We used to have the CMRR on our Skyra, but had to change to Siemens MB with the upgrade Skyra->VidaFit, initially with syngo XA20. Recently we received the XA50 (SP1) update.
I would be happy to offer any help with beta testing on an XA50 platform!

Thanks!
Jochen

**Comment by axthi** [comment]
Hi - also our site is looking forward to a XA50 version of the CMRR multiband EPI, and I was wondering whether there are updates on the expected release date? We would be happy to beta-test, of course, if that would be helpful.

Best regards,
Axel

**Comment by eauerbach** [comment]
The XA50 version will be available later today or tomorrow, check the web site.

**Comment by axthi** [comment]
Exciting! Many thanks for letting us know.

**Comment by robflintham** [comment]
Thanks for you work on this - much appreciated! I'll let you know if we hit any problems with it following our upgrade.
