### ISSUE TITLE
CMRR multiband R2016 licence 23/24

### ISSUE THREAD

**Issue by LiMRIC** [CMRR-C2P/MB#310]
Hi Is anyone else having any issues with running the multiband C2P sequences on the new licence or am I doing something stupid here and missing something?

**Comment by rwmair** [comment]
I put the new license on our scanner about 2 weeks ago, and no issues so far that I've been made aware of. We're running 8-10 hours a day or more with virtually every session using the CMRR MB-BOLD sequence.
