### ISSUE TITLE
Saving acquisitions as volumes instead of slices

### ISSUE THREAD

**Issue by uaMRI** [CMRR-C2P/MB#312]
We went from VE11E to XA30 platform at our site earlier this week. I was able to install the CMRR sequence and licenses without any issue.
However, I noticed a change in the way data was handled for storage and transfer – 

- On VE11E, the BOLD data was stored as 260 images (TRs) with all 76 frames (slices) combined into volumes which gave me 260 images for archival. Same was the case with DTI where I had 76 volumes each with 87 slices stored as 76 volume images.

- On XA30, each frame is stored separately, which is resulting in large number of files for diffusion and BOLD, with each BOLD acquisition consisting of 19836 (261x76) files and DTI with 6612 files. This slows down the network to a crawl when I start data export.

Is there a setting which allows us to combine all the slices like it did on VE11, either in Admin Portal or in the examcard for CMRR sequences?

**Comment by mharms** [comment]
How exactly did you export the data?  See https://github.com/rordenlab/dcm2niix/issues/236

If you used a `File System` export, use `Enhanced` mode for the export.
If you used a `Network` export to a DICOM node (e.g., XNAT or PACS system), you'll need to change the options stored as part of the DICOM node settings.  (Or create a new node that does not turn on the "Multiframe" option).

**Comment by mharms** [comment]
Yes, try just not checking any of the boxes/options under the DICOM node "Storage Settings".

**Comment by mharms** [comment]
![dicom-node-settings-enhanced](https://user-images.githubusercontent.com/3878918/217298625-0b6a589b-1551-4bd1-a89d-258edcac8635.png)
