### ISSUE TITLE
Error  installing CMRR_MB_EPI_XA30A_R017pre5 on prisma XA30A

### ISSUE THREAD

**Issue by jim-uofu** [CMRR-C2P/MB#317]
Update three hours after posting:
One of our pulse sequence programmers got this to work by using the directions in the IDEA manual, p. 52-53, for installing the certificate, instead of the ones in Install_Instructions_Numaris_X.pdf  The differences are slight, and I will verify with him before posting them.

Thank you for working so hard to keep CMRR code available!

After our prisma was upgraded to XA30A we followed the instructions in Install_Instructions_Numaris_X.pdf to install CMRR_MB_EPI_XA30A_R017pre5. The first page went great, and installing the provided certificate generated no errors.

When we tried to run the installer (INSTALL_CMRR_MB_EPI_NX.exe) we got this error:
 
"An error in a system binary was detected. Try refreshing the PC to fix the problem." Rebooting the prisma PC did not help.
 
The error we got seems to be a microsoft windows error. Has to do with setting up "device guard". See this link below, and there are many other web pages that refer to it when people try to install python and other applications on PCs:
 
https://social.technet.microsoft.com/Forums/windows/en-US/1e83efb9-d8c9-4569-89c0-b8501a346961/issue-while-enabling-device-guardan-error-in-a-system-binary-was-detected-try-refreshing-the-pc

One contact at Siemens suggested "Device Guard is a certificate signature problem.   Either the developer’s certificate is not installed on the machine or there is a certificate mismatch.   That would be my guess. "

Thoughts anyone?

Jim

**Comment by eauerbach** [comment]
The instructions in the Install_Instructions_Numaris_X.pdf are essentially taken directly from the IDEA manual (with some additional clarifications), so this is surprising

**Comment by eauerbach** [comment]
I can only assume the certificate actually didn't get installed correctly. Please try to install the new R017pre6 version that will be on the web site today or tomorrow, following the updated instructions. Then note as explained in the instructions that the installer exe can only be run after the system is rebooted following the certificate install, and then only as administrator (e.g. from an Admin Cmd shell or right clicking and selecting run as administrator).

**Comment by jim-uofu** [comment]
Eddie,

Yes, by following the instructions for CMRR*R017pre6 everything installed correctly on our prisma XA30A and the sequence ran. However, along the way something odd happened at our site that may happen to others.

Our scanner began throwing windows operating system errors, telling us we weren't allowed to open the "admin cmd" window. This was odd, because right after the initial XA30A install, there was no problem opening "admin cmd". We could not figure out what had changed.

We were given a work-around from Siemens to get an elevated command window:
Runas /user:MRC35017\medadmin cmd
This got us part way into the certificate process, but failed long before the end.

Our Siemens engineers had no idea why the operating system had decided we couldn't invoke the
"admin cmd', so they recommended a full software reload on the PC. This is the second full software reload we have had since the original XA30A upgrade on March 6, so that's two software reloads in 5 weeks.

I asked the Siemens engineers if they had a way to test for bad sectors on the host PC disk, in case that was the reason for the errors, but they did not. Software reload was the only tool they had.

A Siemens employee that is partly based at our site says he knows of other XA30 sites that had to reload the host PC software to get things to work, so it seems we are not alone.

Finally, I learned that step 13 on the install instructions, "Reboot the system to activate the new policy", needs to be a full shutdown and reboot. I tried the shorter "restart workplace" and that did not work, but that was a minor delay compared to our operating system woes.

Jim

From: Eddie Auerbach ***@***.***>
Reply-To: CMRR-C2P/MB ***@***.***>
Date: Monday, March 27, 2023 at 4:03 PM
To: CMRR-C2P/MB ***@***.***>
Cc: James Lee ***@***.***>, Author ***@***.***>
Subject: Re: [CMRR-C2P/MB] Error installing CMRR_MB_EPI_XA30A_R017pre5 on prisma XA30A (Issue #317)


I can only assume the certificate actually didn't get installed correctly. Please try to install the new R017pre6 version that will be on the web site today or tomorrow, following the updated instructions. Then note as explained in the instructions that the installer exe can only be run after the system is rebooted following the certificate install, and then only as administrator (e.g. from an Admin Cmd shell or right clicking and selecting run as administrator).
