### ISSUE TITLE
VA30

### ISSUE THREAD

**Issue by dardotomasi** [CMRR-C2P/MB#322]
Hello,

At the NIH, we have been utilizing the CMRR multiband EPI C2P since 2015 on a Prisma scanner operating on D13D, which is based on Windows 7. Our IT department has recently requested a transition to Windows 10. We have been considering the use of Siemens Evolve, which will upgrade the system to NX VA30. We are curious to know if the C2P is compatible with this new baseline. Additionally, we would like to inquire whether the sequence version for the new baseline differs from the currently installed version.

Thank you in advance for your assistance. Have a great day!

Dardo

**Comment by eauerbach** [comment]
Yes, the R017 prerelease is available for XA30. It has some new features and fixes compared to the R016 version available for D13D. Theoretically, if you use the same protocols, R016 and R017 should behave the same, but D13D vs. XA30 is a massive change at the system level.
