### ISSUE TITLE
issues about XA30

### ISSUE THREAD

**Issue by welton0411** [CMRR-C2P/MB#323]
We tried to use the XA30 version of fMRI sequences. The sequence ran well but we couldn't use physio recording (under the tab of 'sequence' -> 'special' ). The option is fixed at 'OFF' and doesn't allow us to select 'DICOM'. How could we activate the 'DICOM' option?

![CMRR_MB_physio_recording](https://github.com/CMRR-C2P/MB/assets/26012548/f59fbc1f-7d29-4cdf-84e8-e91e3117065b)

**Comment by mharms** [comment]
Are you sure that you have the "R017pre6" release installed, and not the "pre5" or earlier?
https://github.com/CMRR-C2P/MB/discussions/288#discussioncomment-5455739

**Comment by welton0411** [comment]
it's true that our sequence is pre5. We downloaded the sequence early this year and didn't realize the new release in April. I have downloaded the sequence and will try again.
