### ISSUE TITLE
XA30 installation problem

### ISSUE THREAD

**Issue by abfeld007** [CMRR-C2P/MB#324]
Hi, we have followed the directions for XA30, and then followed the instructions for (B)  the app has been blocked by your administrator. When we followed the instructions to execute the installer as Administrator from both methods we get this error: 

![Siemens_error](https://github.com/CMRR-C2P/MB/assets/36004922/b0be29b1-a95c-405b-a048-28d84d80282f)

**Comment by eauerbach** [comment]
Please download a new copy of the installer, this is fixed in the latest version. On Jul 19, 2023, at 1:40 PM, abfeld007 ***@***.***> wrote:﻿
Hi, we have followed the directions for XA30, and then followed the instructions for (B)  the app has been blocked by your administrator. When we followed the instructions to execute the installer as Administrator from both methods we get this error:

**Comment by abfeld007** [comment]
We tried again by deleting the copy and starting installation from the beginning (before this message), and it CRASHED our scanner. Down for 5 hours while a back up from another scanner was used to restore it. We saw the yellow warning box, but this had not happened the first 7 attempts and we thought we were okay. So the big question is the patch also complete for XA30?

**Comment by abfeld007** [comment]
Actually, since I re-downloaded the installation package yesterday, I probably did use the new copy of the installer, which caused our scanner to crash  - and the need to be restored from a back up. Is there an update on the patch for XA30?

**Comment by abfeld007** [comment]
Actually, since I re-downloaded the installation package right beforehand,
I probably did use the new copy of the installer, which caused our scanner
to CRASH hard. We had to restore from a backup. So the big question is.. is
there an update on the patch for XA30?

**Comment by eauerbach** [comment]
I don't see how it is possible for the installer itself to crash the scanner, but the certificate installation process is known to have this problem. If you already installed the certificate once, it is not necessary to do it again. You can just run the installer and skip the certificate steps. The latest version of the sequence has updated instructions.

**Comment by abfeld007** [comment]
Thank you Dr. Auerbach for your response. 
Since it is the same problem previously reported with the certificate installation process that led to the fatal error... we needed to restore from a back up from a different MRI scanner so I was assuming the certificate was not actually installed, and we would need to reinstall the certificate. Are you saying there is a way to install the certificate, create a backup point before rebooting, and then restore from backup after that?

Second, I re-downloaded the CMRR_MB_EPI_XA30A_R017pre6 file just now for the latest version. The Multi-Band_C2P_Instructions.pdf has the same 7 points in the instructions. So I double-checked the Install_Instructions_Numaris_X.pdf file, and the 19 points there as well as the 2 for installing sequences are also the same. Perhaps I am missing something.
