### ISSUE TITLE
XA50 SP01 vida fit .exe not working

### ISSUE THREAD

**Issue by erpoul** [CMRR-C2P/MB#328]
Hi, we were able to install the certificate without issue, but when we run the install .exe from the following release CMRR_MB_EPI_XA50A_R017pre6 the installation seems to complete, at least no bug seen, but nothing was added to customer sequence. It seems the .exe did nothing. We have run the install from temp as well as from a usb key without success. After rebooting we have the exact same issue ?

**Comment by negya** [comment]
Hi there,

We had the same issue running the installer on a XA50 Vida scanner. 
The installer page would close quickly, so we were not able to see if there were any issues. 
However, the issue arises from the .bat file in the batch folder that come with the installer not determining the signatures correctly. We were able to resolve this by hardcoding the signatures:

set scanner_signature="NXVA50A"
set sequence_signature="NXVA50A"

in the .bat script. 
after this modification, the installer script should run successfully and copy the files in their destinations. 
hope this helps :)

**Comment by erpoul** [comment]
Hi, thank you very much, it was in fact the problem and we were able to install after the following modification:

        for /f "usebackq" %%i in ("%temp%\SeqSigRead.txt") do set scanner_signature="NXVA50A"
        for /f "usebackq" %%i in ("%temp%\SeqSigRead.txt") do set sequence_signature="NXVA50A"

**Comment by eauerbach** [comment]
This should be fixed in the next version of the installer (pre7), no need to edit the script going forward

**Comment by eauerbach** [comment]
Are you sure the certificate is installed?

**Comment by jhirschAtMEVIS** [comment]
Yes indeed, the certificate was not yet installed; I haven't read the manual carefully enough and was distracted by an error message that looked different from the manual. And the "Device Guard"  is mentioned in context with XA30/XA31 (the yellow box) which I skipped due to our XA50 version. I'm sorry.
All is fine now, and we are looking forward to integrating it in our neuro scans.
