### ISSUE TITLE
pre7 on XA30 - not saving images!

### ISSUE THREAD

**Issue by peter-mri** [CMRR-C2P/MB#335]
I've just installed pre7 on our Siemens Prisma with XA30. When I turn on saving physio log in DICOM, only physio log is saved - but no actual images!!! Only when physio logging is off, images are saved.

**Comment by eauerbach** [comment]
oops

**Comment by eauerbach** [comment]
I left a debugging option on, I will fix that and re-upload

**Comment by eauerbach** [comment]
ok, it should work now, sorry about that

**Comment by peter-mri** [comment]
Thanks, it works ok now. I've noticed that DICOM tags where data are stored has changed - image type is ORIGINAL\PRIMARY\OTHER\NONE and data are stored in Private_7fe1_1010

**Comment by eauerbach** [comment]
Yes, I am not sure it makes any difference in performance or reliability, but I changed the tag to match what Siemens uses in their WiP. I updated the sample Matlab reader code to account for this (4c8176401f9ac9290185a4ab7c73b159a86c0650)
