### ISSUE TITLE
XA30 sequence isn't performing a frequency adjustment at the beginning of the scan when using R017pre7!

### ISSUE THREAD

**Issue by PaulGaalman** [CMRR-C2P/MB#336]
Yesteday, (Oct 11th 2023) I downloaded & installed (without any errors) CMRR_MB_EPI_XA30A_R017pre7 on Skyra running XA30A.
A test showed (3x EPI MB6 TR 1sec 600 volumes) a drift is still visible in the Y direction. For all scans the option to confirm manually the adjusted frequency was enabled. At scan 2 and 3 the frequency was not adjusted while a drift in Y direction was cleary visible.  Hence, to me the issue is not solved (or implemented) with R017pre7. Maybe (hopefully) the solution to this issue was not implemented yet!

![Github](https://github.com/CMRR-C2P/MB/assets/91669438/3577464c-dd6a-47f7-8bde-0497d1a732ab)

**Comment by eauerbach** [comment]
I updated the sequences for XA30 with a possible fix for this issue. I can see how it is possible that existing protocols would not have been repaired, but new protocols would work as expected. The new version on the web site dated 24-Oct-2023 hopefully fixes the issue with existing protocols.

**Comment by mharms** [comment]
The behavior under the "24-Oct-2023" version appears to be as desired regarding the frequency adjustment (i.e., back to the behavior under VE11).

- Per review of `twix`, we got "AdjFre" scans prior to all of the CMRR SE, BOLD, and DIFF sequence scans on an XA30 Prisma.
- This was true for both an XA30 protocol freshly installed (from exar1; after installation of the "24-Oct-2023" version), as well as for a protocol that was already existing on the scanner prior to installing the "24-Oct-2023" version of "pre7".

**Comment by PaulGaalman** [comment]
As MHarams I also come to the same conclusio! No "image drift" visible anymore! Thanks Eddie for solving this issue!
