### ISSUE TITLE
`readCMRRPhysio.m` parses the *.log files : no option to skip this part

### ISSUE THREAD

**Issue by benoitberanger** [CMRR-C2P/MB#340]
Hello,

With this commit 8483cce, `extractCMRRPhysio.m` have been removed, replaced by `readCMRRPhysio.m`.
However, `readCMRRPhysio.m` has no option to just write the `*.log` files and stop. It is **always** parsing `*.log`, taking a lot unnecessary time.

At the moment, the best option to simply convert the dicom to log files is to use old function `extractCMRRPhysio.m`.

Is it possible to add on option skip the parsing ?

Thanks a lot,
Benoît

**Comment by eauerbach** [comment]
Ok, I just made an update: if you write the .log files but do not select the option to plot the traces nor specify a return argument to store the traces in a struct, it will now stop after writing the log files. Also now the second argument to plot the traces is optional.

For example:

- `readCMRRPhysio('input.dcm', '/path/to/output')` this special case will only save .log files
- `physio = readCMRRPhysio('input.dcm', '/path/to/output')` will save .log files, parse the traces, and return the traces in `physio` struct
- `readCMRRPhysio('input.dcm', 1, '/path/to/output')` will save .log files, parse the traces, and plot the traces

**Comment by benoitberanger** [comment]
Thank you !
This is very convenient now.

Best,
Benoît
