### ISSUE TITLE
Request - Support for XA60

### ISSUE THREAD

**Issue by josephholtrop** [CMRR-C2P/MB#343]
Hello,

We are getting a new Prisma and it is coming with XA60.  Is there a plan to release the MB-EPI sequence for XA60 and if so in what time frame?

We appreciate the work that is involved in upgrading the sequence and we hope to continue using it on future software platforms.

best,
Joe

**Comment by jmatthews-rotman** [comment]
We are now being offered this upgrade on our PrismaFit as well. XA60 is supposed to fix some workflow issues with unrelated Siemens products, so there is incentive for us to do this upgrade. It would be great to get a sense for how easy/difficult this support will be for C2P developers in general. Not sure if the folk here are involved, but it would be interesting to know about XA60 support for the CMRR Spec sequences as well.

**Comment by eauerbach** [comment]
I currently have a couple versions of XA60 IDEA, but I am not sure if any are the final release version. I also do not have any of the additional source code that I would need to build anything yet. Once I have everything from Siemens I will make a XA60 version.

**Comment by eauerbach** [comment]
XA60 is released
