### ISSUE TITLE
3D EPI option lead to reconstruction error for DWI in VE11C

### ISSUE THREAD

**Issue by julfou81** [CMRR-C2P/MB#344]
Hi,

Thank you again for this extremely useful sequence.
For testing purposes, I tried the 3D option offer by the sequence. It is working well for bold images, but I keep getting "image reconstruction errors" when I try the diffusion variant, for any option I choose: single slab, multi slab, with/witout parallel excitation.

Is there anything special to do to be able to use the 3D option for DWI for this sequence?

Below is a screenshot of the log viewer show an extract of the error messages...

Thank you for your help!

![bug_3D_SE_EPI_recon2](https://github.com/CMRR-C2P/MB/assets/32452352/7501c049-a038-44e5-b172-974aa9d10bd8)

**Comment by eauerbach** [comment]
I am looking into it, the 3D diffusion reconstruction has some problems specific to VE11/VE12

**Comment by eauerbach** [comment]
I think these should be resolved, can you reopen if they are still present in the latest build
