### ISSUE TITLE
Mosaic formation issue with CMRR multi-band? 

### ISSUE THREAD

**Issue by abfeld007** [CMRR-C2P/MB#345]
Hi Dr. Auerbach, We successfully installed R017pre7 to our XA30A Siemens Skyra (and worked well previously on VE11C). Once we had completed the scan the sheer number of files and overall volume was too large for our PACS system, which prevented time-critical clinical exams from being sent to PACS.  I believe the problem is that mosiac formation is not being used and we got one image for every slice. Where do you think the problem is? Is it a problem with CMRR multi-band sequence, XA30, our MaRS or the Siemens Skyra? Thanks, Abid

**Comment by mharms** [comment]
This is actually a problem with the PACS system itself.

You can reduce the number of DICOMs/files dramatically by making sure that you are exporting as "Enhanced DICOMs".  On the settings for the "DICOM Remote Node Editor -> Storage Settings" that means that you want to make sure that none of the options related to "Multiframe Conversion" are activated.

Unfortunately, once you do that, you may find that your PACS isn't equipped to deal with Enhanced DICOMs either, in which case you'll need to work with your PACS vendor to develop a solution.

**Comment by abfeld007** [comment]
That makes sense. I will deal with the PACS issue. But I believe there is an additional problem before it even gets PACS. I downloaded the data with a thumbdrive before I sent it to PACS. For this sequence it is SMS 4 and 4 TE's for each scan. When I reviewed the data this morning, within each run each TE has its own .dcm file with 56 images. When we had VE11C, in the middle of the scan, when we would pull up the images on the scanner it would show a mosaic of that volume. Everything is separate here. 
<img width="423" alt="Screen Shot 2024-01-07 at 9 39 16 AM" src="https://github.com/CMRR-C2P/MB/assets/36004922/7e46beb0-c08a-40a5-803e-2f8836b56599">

**Comment by mharms** [comment]
XA30 does not store images in the old "mosaic" format.  That said, there is an option in the View&Go window to show a given series as mosaic-style within the viewer, if you want to review all the slices within a volume simultaneously (which is indeed useful).

**Comment by abfeld007** [comment]
Thank you. I have one last question along these lines. I found out that our scanner, when it was on VE11C used a Siemens package called "Inline BOLD" which allowed for the old mosaic format. Does this mean that XA30 does not use Inline BOLD? Was there a replacement/upgrade to this? Because my understanding is that it not only for viewing, but Inline BOLD compressed/organized the data coming off the scanner before it sent the files to the machine.

**Comment by mharms** [comment]
I can't comment on the changes to the various package names between VE11 and XA30.  All I know is that the old VE11 "mosaic" format for saving DICOMs no longer exists for XA30 -- to my knowledge there is no XA30 package that restores that aspect of VE11.

The "mosaic" format was essentially a Siemens-specific hack to reduce the number of files for 2D EPI scans. Enhanced DICOM is now the mechanism to accomplish that, thence the mosaic-format was dropped.

What you are experiencing is totally expected, and not an issue with the CMRR MB sequences.

**Comment by abfeld007** [comment]
thanks!
