### ISSUE TITLE
R017 license issue

### ISSUE THREAD

**Issue by iidree** [CMRR-C2P/MB#351]
Hi,

We tried to load the R017 license for the XA30, however, we receive a Code 7 error code (please see attached image). Any assistance with resolving this issue would be greatly appreciated.

Many thanks and best wishes,
Iman
![IMG_2250](https://github.com/CMRR-C2P/MB/assets/143722569/369ac365-4baa-4e53-ab6c-4e0aafd79583)

**Comment by eauerbach** [comment]
Please just try downloading a new copy from the web site, this error indicates the file is corrupted
