### ISSUE TITLE
Options for selecting PE direction

### ISSUE THREAD

**Issue by RishiUA** [CMRR-C2P/MB#354]
In the routine tab of exam card there is an option to select phase encoding direction (A>>P, P>>A, etc.). While reading the document for MB-EPI, I noticed that there is another option in Sequence-> Special tab where we can set the RO/PE either ON or OFF. 
Which of these options needs to be selected for selecting the phase encoding direction? If RO/PE is set to OFF, can we select the correct direction from dropdown menu in Routine tab?

**Comment by mharms** [comment]
Leave it as "A>>P" in the Routine, and invert it to "PA" using the option on the Special Tab, which exists as a work-around to avoid a bug in the Siemens user-interface that has a bad habit of converting a "P >> A" setting on the Routine to "R >> L" (or perhaps it is "L >> R" -- either way, not what you want).

**Comment by RishiUA** [comment]
That is extremely helpful to know. I'll change the encoding direction using options on Special tab as you recommended.







Rishi Deshpande
________________________________

Technical Director | UA MRI Research Facility | The University of Alabama<https://www.ua.edu/> | 205.348.5066

________________________________
From: Michael Harms ***@***.***>
Sent: Wednesday, March 20, 2024 5:28:39 PM
To: CMRR-C2P/MB ***@***.***>
Cc: Rishi Deshpande ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [CMRR-C2P/MB] Options for selecting PE direction (Issue #354)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Leave it as "A>>P" in the Routine, and invert it to "PA" using the option on the Special Tab, which exists as a work-around to avoid a bug in the Siemens user-interface that has a bad habit of converting a "P >> A" setting on the Routine to "R >> L" (or perhaps it is "L >> R" -- either way, not what you want).
