### ISSUE TITLE
Installation not possible on XA60

### ISSUE THREAD

**Issue by pimpul** [CMRR-C2P/MB#358]
Hi, 

Our system was upgraded to XA60 BL8. I'm trying to run the installer exe file, but the system won't let me run it. I've tried `Run as Administrator` as well as in the Admin Cmd terminal:

![CMRR_XA60](https://github.com/CMRR-C2P/MB/assets/15831740/181a1314-8f8c-45b6-a307-43a185f986b4)

How can this be resolved?

Best,

Pim
Ghent University, BE

**Comment by pimpul** [comment]
BTW I tried also to run the installer from the `K:\Temp\` directory, without success.

**Comment by pimpul** [comment]
Problem solved. The trick is to install the certificate belonging to the exe file:

`DeviceGuardPreparation.ps1 [installer.exe]`

Best,

Pim

**Comment by eauerbach** [comment]
There should not be a trick? It should work if you install the certificate as described in the instructions? Sure, you can alternatively install the certificate from the .exe file, but it is the same certificate, it should be the same as using the .cer file.

**Comment by pimpul** [comment]
When I installed the certificate from the .cer file, it wouldn't let me run the .exe file. I really had to install the certificate from the .exe as described.

**Comment by eauerbach** [comment]
That is interesting, maybe the problem is running it from anywhere under `K:\`. I usually test from `C:\Temp` or directly off of a flash drive.
