### ISSUE TITLE
Noise scans in R017pre6 for VE12U-AP02-F23

### ISSUE THREAD

**Issue by ajsbeckett** [CMRR-C2P/MB#359]
We are using the MB-EPI sequence version for the Terra Impulse (R017pre6, VE12U-AP02-F23). I've seen some references to being able to collect noise scans (without excitation) at the end of an acquisition for use in NORDIC processing, but am not able to find an option to do so in any of the tabs on the GUI. Is this option included in the version of the sequence we have, and if so is there something additional I need to do to make the option available in the sequence?

**Comment by eauerbach** [comment]
I added a description to the Wiki for how to enable this option.
