### ISSUE TITLE
XA30A: Excite & Refocus pulse duration parameters missing from GUI for cmrr_mbep2d_se

### ISSUE THREAD

**Issue by BenInglis** [CMRR-C2P/MB#360]
Excite pulse duration is present and usable on the Sequence/Special card for cmrr_mbep2d_bold but not for either *_se or *_diff sequences. 

Prisma
XA30A 
R017pre7

**Comment by BenInglis** [comment]
Found working for _diff, still not for _se despite different starting points.

**Comment by eauerbach** [comment]
The original intent was that those parameters only appear when MB is enabled, not sure if that is consistent with what you are seeing

**Comment by BenInglis** [comment]
Aha! That works. Trying to get a Caltech NHP protocol running. May I assume that if I set MB=2, change the Excite & Refocus pulse durations, change everything back for MB=1 that the updated durations will stick? Thanks!

**Comment by eauerbach** [comment]
Unfortunately no, in SB mode it uses the Siemens default. This was a decision we made a long time ago where in SB mode the sequence would closely match the product. So you can only change the RF pulse type (Fast, Normal, Low SAR).

If you really need thinner slices than can be achieved with the standard parameters, maybe we can figure something out.

**Comment by BenInglis** [comment]
Thanks. Understood. Okay, then let me swim upstream a bit farther. Perhaps my NHP folks didn't have the slice thickness they thought they had when at Caltech. I'll close this issue and get back to you once I understand more. Thanks for the offer to figure something out. Shouldn't be needed, we're just trying to match what they claim they had elsewhere. Cheers!
