### ISSUE TITLE
XA60 installation successful, but can't see sequences in the sequence explorer

### ISSUE THREAD

**Issue by mattwall1103** [CMRR-C2P/MB#361]
Hi all,
Just installed the XA60 version on our new Siemens Vida and everything seemed to go smoothly, but we've hit one final snag. The sequence .dll and .so files are visible in the Windows file system (on the K: drive) but we can't seem to access them from within the XA60 software. Previously they would appear in the sequence explorer/editor under the DEFAULT USER list, but that's not the case. Under older versions of Syngo there used to be a C:/Medcom/CustomerSeq/ folder that held everything but C:/Medcom seems not to exist with XA60.

Is there another location in the file system we need to copy the sequences to, so that XA60 can find them and show them in the sequence explorer? Something else we're not doing right?

Any help very much appreciated - thank you.
Matt.

**Comment by eauerbach** [comment]
Did you use the installer? Are you sure you have the IDEA license? The installer tries to warn you, but I have heard it is too easy to just click through.

**Comment by mattwall1103** [comment]
Hi - thanks for getting back. We used the installer, followed the installation instructions very carefully, and I'm told that we do have an IDEA license. We didn't notice any messages about that as we were installing, and we we took it slowly and were quite careful with it. It seemed like the installer worked perfectly, but we just can't 'see' the sequences from within the XA60 software. Any other ideas?
Thanks again,
M.

**Comment by eauerbach** [comment]
If you able to use any other customer sequences then the IDEA license must be installed, but if you are not sure then it is the most likely thing to question. I think my license detection code in the installer works, but I have never used XA60 so it is possible there is an issue with it there.

Are you able to run the product ep2d_bold, ep2d_diff, ep2d_se sequences? Maybe there is some other license missing.

Maybe you can get some more information by opening a command prompt and entering this command:
`crdefprot -s %customerseq%\cmrr_mbep2d_bold -p test.pro`

**Comment by mattwall1103** [comment]
Thanks for your help. This is a brand new scanner we're trying to set up so we haven't tried to install anything else yet. We can run the product sequences no problem though. 
Will check our IDEA license situation and try that command - thanks again.
