### ISSUE TITLE
CMRR sequence installation fails

### ISSUE THREAD

**Issue by nabinkrl** [CMRR-C2P/MB#366]
Hi all, We just updated our Siemens Prism (3T) with XA60 and are trying to install the cmrr sequences. Unfortunately, we are running into the issue where it says the windows defender is blocking the app to execute. I tried some suggestions found online (like installing the certificate first etc.) but nothing has worked so far. Any suggestions would be very much appreciated. 

Thanks,
Nabin

**Comment by nabinkrl** [comment]
This was resolved by installing the certificate again following the steps mention in the manual. Somehow did not work first time around. But we have now the issue that the installation is successful but it does not show up in the Kiosk tree. Now sure what is going on. Any comments will be appreciated. 
Thanks,
Nabin

**Comment by eauerbach** [comment]
If the installation is successful the default protocols should appear in the DEFAULT protocol folder. If not, the most likely reason is if the IDEA license is not installed. The installer checks for the IDEA license, but it is maybe too easy to ignore the warning.

**Comment by eauerbach** [comment]
You can try to manually create a default protocol as described here: #361

**Comment by jmatthews-rotman** [comment]
I just ran into this same issue after upgrading from XA30 to XA60, and I think it just requires a documentation update for XA60. 
Right now the documentation labels the Windows Defender popup as message C and attributes it to the installer being run from the wrong location. However it appear that on XA60, this is also the popup you will see if the license is not installed. running the installer from the same file location was possible after doing the license installation. So popup (C) can also indicate the license is not installed if on XA60 (and possibly others).

<img width="1920" height="1203" alt="Image" src="https://github.com/user-attachments/assets/80f3748a-8f77-4c7b-8183-7f5e386e869a" />
