### ISSUE TITLE
PrismaFit XA30; Recon error

### ISSUE THREAD

**Issue by atl404** [CMRR-C2P/MB#368]
I have installed the CMRR MB sequences on a PrismaFit running XA30 and am trying to use a protocol that was sent to me by a different institution who are using the CMRR MB sequences on a Prisma running VE11C software. The protocol imported without any issues and I checked the parameters against a PDF file and they were fine. However, when I try to run either the DTI MB sequence or the fMRI MB sequence the acquisition fails immediately after the preparation phase (the preparation is complete, the frequency adjustment after the shim completes as normal) with a recon error. I tried dropping the MB factor on the DTI sequence from 3 to 1 but that made no difference, nor did lengthening the TR and TE. Do you have suggestions as to what the problem may be and are the differences between a Prisma and PrismaFit significant in terms of required protocol changes?

**Comment by atl404** [comment]
Just adding some information from the log file
 
![image](https://github.com/CMRR-C2P/MB/assets/62623350/f2f7d733-91e3-470b-99a9-44ad7ba75861)

The ice file mentioned in the second error message is not present so that would seem to imply that something went wrong during the installation by the Install program. Is there a list of what files should be where that I can refer to in order to check if other files are missing. I'm not sure I understand the first error message.

**Comment by eauerbach** [comment]
If the ipr file is indeed missing, then the installation definitely failed. I would recommend downloading the latest version and trying to run the installer again. It displays the list of files it attempts to install and you should see error messages if any of the copy operations fail.
