### ISSUE TITLE
EPI_noise_scans option missing in XA30?

### ISSUE THREAD

**Issue by CesarCaballeroGaudes** [CMRR-C2P/MB#375]
Hello,

We have upgraded the sequences from VE11E to XA30, and noticed that the EPI_noise_scans option is missing in the XA30 version of the BOLD sequence.  Has it been removed? We would like to run NORDIC with noise scans. 

Thanks,
César

**Comment by eauerbach** [comment]
It is hidden by default, you need to enable it in the ini file, please see the wiki

**Comment by CesarCaballeroGaudes** [comment]
Hello @eauerbach, could you please let me know which folder the config file MBAdvancedSettings.ini should be located in XA30?
I have tried to put it in the following folder without success
`C:\Program Files\Siemens\Numaris\Mars\MriCustomer\CustomerSeq`
This is the same folder where the .dll and .so files of the sequence are also placed. 
The MBAdvancedSettings.ini config file is as simple as
```
[Multiband]
EPINoiseScan = 1
```

**Comment by Jolinda** [comment]
@CesarCaballeroGaudes did you sort this out? I'm having the same trouble and I'm wondering if there's something else I need to do.

**Comment by CesarCaballeroGaudes** [comment]
It was sorted out in the newest version of the sequence. Please refer to @eauerbach
