### ISSUE TITLE
Xa60 unable to start sequence 

### ISSUE THREAD

**Issue by karenkett** [CMRR-C2P/MB#381]
If the physio logging is set to anything other than off or legacy mode the sequence will not start. No error messing log viewer or to user sequence just fails. 
![IMG_0649](https://github.com/user-attachments/assets/7a7dafbf-cfda-4e28-9713-e3931ee8b24f)

**Comment by eauerbach** [comment]
This can be fixed by installing the patch here: https://github.com/CMRR-C2P/MB/issues/367#issuecomment-2259219540
