### ISSUE TITLE
Multi-echo FMRI

### ISSUE THREAD

**Issue by inati** [CMRR-C2P/MB#43]
Hello,

We've been doing a lot with multi-echo FMRI recently and would like to see this incorporated into the multi-band GRE sequence.  I know it adds a significant overhead to the recon, but it would be a great feature.

-Souheil

**Comment by rjgenik** [comment]
Is Multi-echo going to be included in the upcoming release, or is the limited site testing phase still ongoing?

**Comment by eauerbach** [comment]
Multi-echo will be fully supported in the next release.
