### ISSUE TITLE
No Embedded_Control_Mode.pdf included in zip disrtibution

### ISSUE THREAD

**Issue by lucijj** [CMRR-C2P/MB#81]
I downloaded the CMRR_MB_EPI_VD13A_R012.zip distribution, and the embedded control instructions are not included as described in the installation instructions.  Could you please provide that document either directly or via the MB download page?

**Comment by edevita** [comment]
Hello,
having the same problem on VE11c 
(require Embedded Control) and the username/password from VB19A does not seem to work.
Any hints?
thank you!
