### ISSUE TITLE
critical Linux OS errors

### ISSUE THREAD

**Issue by TimmWetzel** [CMRR-C2P/MB#82]
We are seeing sporadic imager errors after a multiband acquisition has finished. (`critical Linux OS error, please create a Savelog.´) The imager seems to log an SIGXCPU at the time of error. Reinstalling and replacing the imager did not help, and Siemens support finally decided that the sequence is at fault.

How can I help debugging this — do you need a savelog?

We are using a Prisma_fit running VD13D with a 128-channel mars.

**Comment by TimmWetzel** [comment]
The above setting indeed seems to fix things for us. Since it is in place those imager errors are gone.

Thanks!

**Comment by eauerbach** [comment]
Fix integrated into the R012b installer scripts.
