### ISSUE TITLE
Invert RO/PE

### ISSUE THREAD

**Issue by gbook** [CMRR-C2P/MB#84]
We noticed that this option has been checked for our sequences, and we have some questions about what that option does. Does the option effectively invert the phase encoding angle? So if we are collecting A>>P, it will actually be collected P>>A, even though the DICOM header implies A>>P?

Currently A>>P is written to DICOM as InPlanePhaseEncodingDirection=ROW and *.dInPlaneRot=0
P>>A is written to DICOM as InPlanePhaseEncodingDirection=ROW and *.dInPlaneRot=3.14159..

Does enabling the Invert RO/PE option really flip the collected phase angle to the opposite of what the DICOM label says? Is there another field in the DICOM that indicates if the flipping was done?

**Comment by eauerbach** [comment]
That checkbox simply applies a 180-degree in-plane rotation. So both the readout and phase encoding directions have swapped polarity. It is exactly the same as if you were to enter a 180-degree in-plane rotation in the user interface, only it is automatically done within the sequence code. It is just a shortcut for protocol automation. If have a predefined protocol where you always want two scans with AP and PA covering the same slices you could not use "copy parameter" to copy the slice positions between them automatically without this option (you would always need to manually enter 180-degree in-plane rotation for one of them which is easy to forget).

**Comment by AlbertoImg** [comment]
Hi CMRR team, 
I would like to ask you where I can find the box "invert RO/PE polarity" at the scanner (To switch on/off). I see it in the pdf protocol, but I could not find it in the "Sequence-Special" card, or any other. 
Thanks!

**Comment by swrieger** [comment]
It's on the sequence special card. Where it says single-band images, if you click on the little triangles, you can scroll through a whole list of parameters, and one of them is invert polarity.

**Comment by AlbertoImg** [comment]
Thanks for the info! I found it there!
