### ISSUE TITLE
Zip file errors

### ISSUE THREAD

**Issue by cjwiggins** [CMRR-C2P/MB#86]
I have downloaded  Release R012 for VB17A-Step2/F15 (CMRR_MB_EPI_VB17A-F15_R012.zip) receive an error regarding the MBIcePrg2D.dll and .so when extracting the files. I tried downloading a second time and got exactly the same error. 

Chris Wiggins
Scannexus, Maastricht

Extracting to "D:\Junk\"
Use Path: yes   Overlay Files: no
Extracting CMRR_MBIcePrg2D.dll
Error: Unable to extract "D:\Junk\CMRR_MB_EPI_VB17A-F15_R012\Ice\CMRR_MBIcePrg2D.dll".

The size of the extracted file (1876058) does not match the uncompressed size (1871962) recorded in the Zip file
Extracting CMRR_MBIcePrg2D.evp
Extracting CMRR_MBIceProgram2D.evp
Extracting CMRR_MBIceProgramDti2D.evp
Extracting libboost_system.so.1.46.1
Extracting libCMRR_MBIcePrg2D.so
Error: Unable to extract "D:\Junk\CMRR_MB_EPI_VB17A-F15_R012\Ice\libCMRR_MBIcePrg2D.so".

The size of the extracted file (57634327) does not match the uncompressed size (57497687) recorded in the Zip file
Extracting install_cmrr_mb_epi_vb.bat
Extracting Multi-Band_C2P_Instructions.pdf
Extracting SaveLog_Instructions.pdf
Extracting cmrr_mbep2d_bold.dll
Extracting cmrr_mbep2d_bold.i86
Extracting cmrr_mbep2d_diff.dll
Extracting cmrr_mbep2d_diff.i86
Extracting cmrr_mbep2d_se.dll
Extracting cmrr_mbep2d_se.i86

**Comment by eauerbach** [comment]
That is strange; it tests and extracts fine with Info-Zip, but reports a CRC error with 7-Zip, across multiple platforms. So you can either extract the copy you have using Info-Zip, or download the updated version I just posted which does not have this issue.
