### ISSUE TITLE
additional RF pulse shape please

### ISSUE THREAD

**Issue by whitecraine** [CMRR-C2P/MB#87]
Hi Eddie,

For pulse shapes, #6 offers 3.2/2.0 BWTP. However, there is no option for 2.0/3.2. This option would seem useful given that it is consistent with the default (3.2/5.2) regarding the refocussing pulse having better slice profiles to define the slice. Could you add it? Or make BWPT a modifiable scalar similar to the Diff. spoil factor?

Thanks,
Joseph

**Comment by eauerbach** [comment]
This is a very old comment, I don't remember if it is still relevant, but in the latest version (R017) selecting the sinc pulse type does indeed open up UI options for entering arbitrary BTWP factors (in the array of double parameters along with the diff. spoil factor).
