### ISSUE TITLE
online motion correction

### ISSUE THREAD

**Issue by TimmWetzel** [CMRR-C2P/MB#89]
We have noticed that the motion correction option does not work properly. The uncorrected image series is fine, but in the moco series for all volumes but the very first the image intensity is clipped at exactly 4095:

![online motion correction bug](https://cloud.githubusercontent.com/assets/9423058/6129201/c78f9044-b13c-11e4-986c-a2398a5b6f69.png)

Seen with cmrr_mbep2d_bold on VD13D.

Regards,
Timm

**Comment by eauerbach** [comment]
For the VDxx versions I have enabled the 16-bit DICOM output to avoid issues with limited dynamic range, but it appears the motion correction does not respect that. Officially in the documentation I say the postprocessing options (BOLD, DTI) are not supported. I can see if something simple can be done about this (I do not have source code for the postprocessing functors), but if you really want to use it and don't care about dynamic range, for now I guess you could adjust the FFT scaling factor to keep the pixel values below 4095.

**Comment by TimmWetzel** [comment]
Dear Eddie,

> On 17.02.2015, at 01:14, Eddie Auerbach <notifications@github.com> wrote:
> 
> For the VDxx versions I have enabled the 16-bit DICOM output to avoid issues with limited dynamic range, but it appears the motion correction does not respect that. Officially in the documentation I say the postprocessing options (BOLD, DTI) are not supported.

yes, I figured that the technical background was the 12-bit processing. 

> I can see if something simple can be done about this (I do not have source code for the postprocessing functors), but if you really want to use it and don't care about dynamic range, for now I guess you could adjust the FFT scaling factor to keep the pixel values below 4095.

I looked in the ICE manual, and it seems that either ICE.CONFIG.DICOM.ImaScaleAndConvert.Convert2ShortBeforePostProc := false might force the EvaProtocol Functors using float input, or failing that maybe autoscaling before inline postprocessing might help (ICE.CONFIG.DICOM.ImaScaleAndConvert.AutoScale := true).

If there is no easy workaround, you should consider just disabling MoCo for the 16-bit platforms — it would probably avoid some ugly surprises.


Regards,
Timm

**Comment by eauerbach** [comment]
I will look into some kind of solution for the next release.

**Comment by eauerbach** [comment]
Ok, this is "fixed" for R013, but there is no ideal solution. No matter what the data format is going into the motion correction decorator (16-bit int, 12-bit int, or 32-bit float), the output is effectively 12-bit. I don't know if it actually converts to 12-bit internally or just applies fixed thresholds that are only appropriate for pre-scaled 12-bit data, but there is no sense in rescaling the data after that. So if one chooses to use the online motion correction, I will simply disable the 16-bit ("high dynamic range") option.
