### ISSUE TITLE
Network connectivity in remote recon

### ISSUE THREAD

**Issue by gbook** [CMRR-C2P/MB#90]
We are attempting remote reconstruction on our Skyra VD13, with a 10G ethernet card. We're using the recommended Myricon cards and cables. We have the remote system (centos 6.4) recognizing the card, and the MARS sees its card as well. Both 10G enet cards have the green link light on. Both machines can ping themselves on the IP address we specified. But, neither machine can ping the other.

For the MARS:
eth2, IP=192.168.2.4, netmask=255.255.255.0

For the remote recon machine:
plp1, IP=192.168.2.5, netmask=255.255.255.0

What might be causing the machines to not be able to see each other?

**Comment by eauerbach** [comment]
192.168.2.1/29 is the scanner internal network, so you have an address conflict... Just change the IP addresses on the 10G network to anything else not 192.168.2.x, e.g. 10.1.1.x.

**Comment by gbook** [comment]
Thanks, that worked. We now have a link lights between the machines and they can ping each other and we can ssh into one from the other. The remote recon isn't working though. The http://localhost:10000 website does not show any activity when refreshing, and the sequence itself stops on the scanner and reports a recon error. Is there an error log we can check on the scanner console or MARS?
