### ISSUE TITLE
RF Clipping

### ISSUE THREAD

**Issue by lucijj** [CMRR-C2P/MB#92]
We are suddenly getting highly reproducible RF clipping error problems with the cmrr_mbep2d_diff sequence.  It has been working normally until a few days ago.  I have rebooted, done full shutdowns, recreated the protocols from scratch (i.e., Insert -> Sequence, and manually input parameters to ensure no cross-contamination).  None of the product sequences have this problem, and the cmrr_mbep2d_bold sequence still works fine, too.  I have the EDX file from a representative protocol with the MB-DTI scan that fails as well as the new protocol I created from scratch.  I have also attached a screenshot of the error dialog.
![image001](https://cloud.githubusercontent.com/assets/5487581/6578086/039c82b6-c710-11e4-862a-51f602856a8b.png)
![image002](https://cloud.githubusercontent.com/assets/5487581/6578089/06c84420-c710-11e4-80e8-d6dfab1c84e7.jpg)

**Comment by eauerbach** [comment]
There isn't anything about the sequences that could cause this to change over time (unless the flip angles or pulse lengths have been changed in the protocol), so assuming you have not changed the protocols, either the required voltage has increased or the maximum allowed voltage has decreased. Typically you use a relatively low flip angle for the BOLD sequence so this wouldn't be noticeable, and product sequences just don't give you any indication when pulses are clipping. So really the question is whether the typical reference amplitude has gone up or if the maximum transmit amplitude has gone down. That could indicate that you have a problem with the body transmitter requiring it to be retuned or replaced.
