### ISSUE TITLE
RF Power Absorption limiter error

### ISSUE THREAD

**Issue by MarkusBarth** [CMRR-C2P/MB#93]
Hi, 
on our system (7T Magnetom, actively shielded) we have the following error when running MB BOLD EPI (release 012) functional MRI (MB factor 2):
RF Power Absorption Limiter Error: RF limit for 5th averaging stage exceeded

Sometimes the scans stop several minutes into the scan, but one can start a new scan, which eventually runs through. Very often the same protocol runs through.

**Comment by benediktposer** [comment]
Hi Markus, 
making he RF pulse somewhat longer will help, and keeping the SAR lookahead below 85% or so. Also switching on the Wong phase relaxation (there's a checkbox in the Special card, I called something like "scramble phase" ), that makes the pulse envelope smoother (not for factor two though there it doesn't help)
The reason for the error is not actually that the SAR is exceeded nor anything wrong with the sequence, it's just that for high SMS factors the pulses are highly modulated, at rates that exceed the "sampling bin size" of the the system's SAR monitoring hardware. Hence one can end up with overestimation of the SAR. This can and will occur very unpredictably at different times during the scan, also for protocols that have (by chance) run just fine for many times. 
I hear  there was also an ISMRM poster from  CMRR about this in Milano.
Cheers Ben

**Comment by eauerbach** [comment]
Yes, unfortunately there is no good solution for this...you have to back off on the SAR until the addition of the measurement error no longer pushes it over the limit. Siemens could upgrade the 7T PALI to the VD-line version that samples faster (the pTx Step 2 PALI is already based on that), but they won't.

**Comment by MarkusBarth** [comment]
Hi Eddie and Ben,

thanks for that very helpful reply, we will do the workaround for now and see what Siemens thinks about it.

Thanks again,

Markus



On 27 Mar 2015, at 13:10, Eddie Auerbach <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, unfortunately there is no good solution for this...you have to back off on the SAR until the addition of the measurement error no longer pushes it over the limit. Siemens could upgrade the 7T PALI to the VD-line version that samples faster (the pTx Step 2 PALI is already based on that), but they won't.
