### ISSUE TITLE
10us jitter in TR on VD13 systems (Prisma)

### ISSUE THREAD

**Issue by benediktposer** [CMRR-C2P/MB#94]
during installation of an EEG system we observed a 10us error in the TR. Nothing to really care about normally, but it causes problems to EEG gradient artefact correction ...
To be clear this is not MB sequence specific bug, but a general bug in the current Siemens EPI sequences. It can easily be fixed as I have now done some sequences here. 

Would be great if this could be resolved for the next MB release to allow simultaneous EEG-fMRI with the MB sequence... :-)
(@Eddie, contact me offline for details if needed)
Cheers, Ben

**Comment by eauerbach** [comment]
It is on the list (I have the info)

**Comment by eddie** [comment]
I think you have the wrong eddie ;)

**Comment by eauerbach** [comment]
This is implemented for the next release.
