### ISSUE TITLE
bug in copying slices from a source scan

### ISSUE THREAD

**Issue by tmildner** [CMRR-C2P/MB#96]
Hello, there is a sequence bug (VD13D and VB17A) that occurs by copying the slices from a source scan into a multi-band EPI scan (DTI or BOLD). The TE of the destination scan will be increased (e.g. from TE=30 to TE=39.4 ms) without any notification (solve handler popup window). The mimimum TE shown and adjusted before copying was, e.g., 30 ms. After copying the slices from a source scan, TE was silently increased to, e.g., 39.4 ms, but the minimium TE shown still is 30 ms. In consequence of this bug, complete studies were measured with inconsistent TE.
Although this bug can be avoided by not copying the slices from the source scan but just the center of the slice package, we hope that it can be fixed in one of the next sequence releases.
Best, Toralf Mildner
MPI for Human Cognitive and Brain Sciences, Leipzig, Germany
mildner@cbs.mpg.de

**Comment by eauerbach** [comment]
I believe this should be solved in R012c
