### ISSUE TITLE
Preparation of Image Reconstruction System failed on Prisma VD13D

### ISSUE THREAD

**Issue by michalmikl** [CMRR-C2P/MB#97]
Hello everybody,

we have installed multiband sequences (version VD13D_R012b) on our Prisma scanners with VD13D syngo version. We have wto almost identical Prisma scanners (main difference si that system A is equiped with multinuclear support). Sequences work well on scanner A. But we have problem on scanner B (similar problem was reported here for older release of MB) - if MB factor is greater than 1, sequence (both diff and bold, we have not tried se) there is error message "Preparation of Image Reconstruction System failed" and we are not able to start sequence. 

Best regards,
Michal

![img_20150619_134544](https://cloud.githubusercontent.com/assets/12966555/8253351/3885eed0-168f-11e5-96c5-47cf68a715c8.jpg)
![img_20150619_134604](https://cloud.githubusercontent.com/assets/12966555/8253356/3bdca0ec-168f-11e5-9d5f-9fc134f46351.jpg)

**Comment by eauerbach** [comment]
Were the sequences/ICE installed only using the included installer batch file? Please check that there aren't any old/duplicate copies of the ICE binaries lingering on the system somewhere. For example, CMRR_MBIcePrg2D.dll should only be in \MedCom\MriCustomer\Ice, but if someone had previously placed a copy in \MedCom\bin (the default path on older syngo versions), the system will attempt to load that copy first (which will cause a crash if it is an older version).

**Comment by ken-sakaie** [comment]
Eddie

I removed all old files and reinstalled the July 8 build.

Error message after shim and frequency adjust:

RF control error: Wrong Triggerraster
Domain: MRI_TXD

Thank you,
Ken

On Jul 8, 2015, at 17:59, Eddie Auerbach <notifications@github.com<mailto:notifications@github.com>> wrote:


Were the sequences/ICE installed only using the included installer batch file? Please check that there aren't any old/duplicate copies of the ICE binaries lingering on the system somewhere. For example, CMRR_MBIcePrg2D.dll should only be in \MedCom\MriCustomer\Ice, but if someone had previously placed a copy in \MedCom\bin (the default path on older syngo versions), the system will attempt to load that copy first (which will cause a crash if it is an older version).

—
Reply to this email directly or view it on GitHub<https://github.com/CMRR-C2P/MB/issues/97#issuecomment-119744163>.

===================================


 Please consider the environment before printing this e-mail

Cleveland Clinic is ranked as one of the top hospitals in America by U.S.News &
World Report (2014).  
Visit us online at http://www.clevelandclinic.org for a complete listing of our
services, staff and locations.


Confidentiality Note:  This message is intended for use only by the individual
or entity to which it is addressed and may contain information that is
privileged, confidential, and exempt from disclosure under applicable law.  If
the reader of this message is not the intended recipient or the employee or
agent responsible for delivering the message to the intended recipient, you are
hereby notified that any dissemination, distribution or copying of this
communication is strictly prohibited.  If you have received this communication
in error,  please contact the sender immediately and destroy the material in its
entirety, whether electronic or hard copy.  

Thank you.

**Comment by michalmikl** [comment]
Thanks for response and suggestion.

We installed the sequences using included original batch file. There was not any older version of MB before this installation. We tried to delete all files (no one was in \MedCom\bin) and to reinstall MB sequences but without any effect.We obtained the same error.

Very first installation was done by my colleague – he told me that installation proces wos not succesfull (but he cannnot remember details) and he had to repeat it (everythink was reported as OK after the second installation). Now, after deleting of files and reinstallation, everythink seems to be correct. But the same error occurs.

Best regards,
Michal

**Comment by eauerbach** [comment]
Ok, I'm not sure what is going on, but if you can reproduce the error then generate a savelog immediately afterwards I can have a look at it. If you don't know how to do this I have included a document (Savelog_Instructions.pdf) along with the sequences; just the *_Developer.zip is enough.

**Comment by michalmikl** [comment]
I have previous savelog prepared for Essa Yacoub. But how can I send the logfile? The size of *_Developer.zip is about 100 MB. Is it possible to upload it on GitHub?

**Comment by michalmikl** [comment]
Dear Eddie,

I only want to report that our issue has been solved. There was hardware problem on Siemens side (wrong one of two GPUs in MARS). It did not affect standard sequences – only MB-EPI. Therefore we did not have any indices for hardware problem  before the findings that this scanner reports only 1 GPU and second scanner reports 2 GPUs.

Best regards,
Michal

**Comment by eauerbach** [comment]
Well, that is interesting. I'm not sure that any of the standard sequences attempt to use multiple GPUs, which could explain why they weren't affected.
