### ISSUE TITLE
HCP Lifespan DWI @ 7T: RF Control Error when Time shifting switched on

### ISSUE THREAD

**Issue by ken-sakaie** [CMRR-C2P/MB#98]
I'm trying to implement the 7T HCP Lifespan protocol on our Siemens Magnetom 7T (actively shielded, step 2). Parameters are essentially the same as those in the pdf from http://lifespan.humanconnectome.org/

When I turn on the Time-shifting option, I get the error:
"RF Control Error: Wrong Triggerraster"
and the sequence does not run.

When I turn off the Time-shifting, the sequence runs most of the way through, but terminates early with the error:
"RF Power Absorption Limiter Error: switched off due to limits exceeded"

Transmit voltage is 260V, which is typical of what we use in vivo.
We're using the NOVA 32 channel transmit/receive.

Any suggestions?
Thanks,
Ken

**Comment by eauerbach** [comment]
The 7T HCP protocol was developed using a different version of the sequences and it turns out the default timings were not matching the C2P (currently R012b). I have updated the R012b sequences for VB17A to fix this (only the cmrr_mbep2d_diff and _se binaries have changed) -- please try these. If you set the "Excite pulse duration" to 5120 us and select the time shifting option it should now use the correct shift of 1920 us to match the HCP protocol.

**Comment by ken-sakaie** [comment]
This reply is the same as my reply to #97. Somehow #97 and #98 got entangled:

I removed all old files and reinstalled the July 8 build. 
Error message after shim and frequency adjust: RF control error: Wrong Triggerraster 
Domain: MRI_TXD 

Any ideas?

Thank you, Ken

**Comment by eauerbach** [comment]
Ok, I see now it is another problem that has been fixed in the newer code we are using in-house but didn't make it into R012b. The problem is actually coming from the GRE iPAT reference when used in combination with the time-shifted RF pulse option.

For a temporary fix, you can change the iPAT reference scan to "segmented". For phantom work there should be no significant difference, but in subjects you are very vulnerable to motion during the segmented EPI reference scan acquisition.

I will try to have a R012c out next week that properly fixes this.

**Comment by ken-sakaie** [comment]
The sequence runs with the segmented option. No RF errors.

Total acceleration is a bit disappointing. I had to increase TR from 5120 to 6461 on the HCP lifespan protocol, which has the time shifted RF.

I eagerly await the updated code!

Let me know if you would like anything else.

Thank you,
Ken

On Jul 10, 2015, at 17:17, Eddie Auerbach <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, I see now it is another problem that has been fixed in the newer code we are using in-house but didn't make it into R012b. The problem is actually coming from the GRE iPAT reference when used in combination with the time-shifted RF pulse option.

For a temporary fix, you can change the iPAT reference scan to "segmented". For phantom work there should be no significant difference, but in subjects you are very vulnerable to motion during the segmented EPI reference scan acquisition.

I will try to have a R012c out next week that properly fixes this.

—
Reply to this email directly or view it on GitHub<https://github.com/CMRR-C2P/MB/issues/98#issuecomment-120531692>.

===================================


 Please consider the environment before printing this e-mail

Cleveland Clinic is ranked as one of the top hospitals in America by U.S.News &
World Report (2014).  
Visit us online at http://www.clevelandclinic.org for a complete listing of our
services, staff and locations.


Confidentiality Note:  This message is intended for use only by the individual
or entity to which it is addressed and may contain information that is
privileged, confidential, and exempt from disclosure under applicable law.  If
the reader of this message is not the intended recipient or the employee or
agent responsible for delivering the message to the intended recipient, you are
hereby notified that any dissemination, distribution or copying of this
communication is strictly prohibited.  If you have received this communication
in error,  please contact the sender immediately and destroy the material in its
entirety, whether electronic or hard copy.  

Thank you.

**Comment by ken-sakaie** [comment]
By the way, the transmit voltage was high but not unrealistic: 260V, Nova 32ch coil

Thank you,
Ken

On Jul 10, 2015, at 18:06, Sakaie, Ken <sakaiek@ccf.org<mailto:sakaiek@ccf.org>> wrote:

The sequence runs with the segmented option. No RF errors.

Total acceleration is a bit disappointing. I had to increase TR from 5120 to 6461 on the HCP lifespan protocol, which has the time shifted RF.

I eagerly await the updated code!

Let me know if you would like anything else.

Thank you,
Ken

On Jul 10, 2015, at 17:17, Eddie Auerbach <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, I see now it is another problem that has been fixed in the newer code we are using in-house but didn't make it into R012b. The problem is actually coming from the GRE iPAT reference when used in combination with the time-shifted RF pulse option.

For a temporary fix, you can change the iPAT reference scan to "segmented". For phantom work there should be no significant difference, but in subjects you are very vulnerable to motion during the segmented EPI reference scan acquisition.

I will try to have a R012c out next week that properly fixes this.

—
Reply to this email directly or view it on GitHub<https://github.com/CMRR-C2P/MB/issues/98#issuecomment-120531692>.

===================================


 Please consider the environment before printing this e-mail

Cleveland Clinic is ranked as one of the top hospitals in America by U.S.News &
World Report (2014).  
Visit us online at http://www.clevelandclinic.org for a complete listing of our
services, staff and locations.


Confidentiality Note:  This message is intended for use only by the individual
or entity to which it is addressed and may contain information that is
privileged, confidential, and exempt from disclosure under applicable law.  If
the reader of this message is not the intended recipient or the employee or
agent responsible for delivering the message to the intended recipient, you are
hereby notified that any dissemination, distribution or copying of this
communication is strictly prohibited.  If you have received this communication
in error,  please contact the sender immediately and destroy the material in its
entirety, whether electronic or hard copy.  

Thank you.
